### ISSUE TITLE
Add information about licensing

### ISSUE THREAD

**Issue by vbauer** [ISchwarz23/SortableTableView#1]

**Comment by ISchwarz23** [comment]
What exactly are you missing about licensing? The copyright on the top of every class?  
Unfortunately I am not very experienced with licensing because this is my first open source library. So maybe you can give me some hints what need to be done in addition to the current state.

**Comment by vbauer** [comment]
I think it will be useful to have some LICENSE file or short information in the README file.

**Comment by ISchwarz23** [comment]
Licens file was added to repository and short desciption about licensing was added to the README :ok_hand:

**Comment by vbauer** [comment]
Thank you!
