### ISSUE TITLE
The dataset have many columns (40+),whether  the table could move horizontally ?

### ISSUE THREAD

**Issue by zhoutonghan** [ISchwarz23/SortableTableView#10]
Thanks your code, it looks powerful!

Now , my dataset have many and many columns,.I want to konw whether the table could scroll horizontally?

many thanks!

**Comment by ISchwarz23** [comment]
Hi zhoutonghan,

first of all I want to thank you for the positive feadback! :)

If you want to do some horizontal scrolling you can do that by simply putting the `TableView` inside a `android.widget.HorizontalScrollView`. The table will work the same way you have experienced before and the HorizontalScrollView enables you the shift the complete table to the left and right.

Kind Regards,
Ingo

**Comment by zhoutonghan** [comment]
Hi ISchwarz23, 

Thank you very much! I will try it .

BEST WISHES!

**Comment by zhoutonghan** [comment]
ps: it may be better,if the data's Gravity in the cell is Gravity.CENTER. I think so.

thank you!

**Comment by ISchwarz23** [comment]
You are free to do so by writing your own TableDataAdapter. All you need to do is to create a new TextView with width MATCH_PARENT and then center the Text inside ;-)
Am 18.01.2016 08:37 schrieb zhoutonghan <notifications@github.com>:ps: it may be better,if the data's Gravity in the cell is Gravity.CENTER. I think so.

thank you!
