### ISSUE TITLE
Cells not visible when tableview inside ScrollView

### ISSUE THREAD

**Issue by ayerkovich** [ISchwarz23/SortableTableView#102]
Hi!

Great library!

Im using tableview inside ScrollView and the only way I managed to show data is fixing a height for the tableView. With MATCH_PARENT and WRAP_CONTENT only shows header.

Thanks!

**Comment by ISchwarz23** [comment]
Hi @ayerkovich,

thank you! I'm glad you like my library.
Yes, this is the expected behavior as the table data is inside a vertical ScrollView.

Best regards,
Ingo
