### ISSUE TITLE
SortableTableView draws over Views below it

### ISSUE THREAD

**Issue by mahye82** [ISchwarz23/SortableTableView#103]
For example, in a layout like this: 
```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.android.fifa17rankings.TableFragment">

    <com.example.android.fifa17rankings.SortablePlayerTableView
        xmlns:table="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/tableView"
        table:tableView_columnCount="8" />

    <TextView
        android:layout_below="@id/tableView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World" />

</RelativeLayout>
```

The SortablePlayerTableView takes data that is read from Firebase Realtime Database (i.e. it's asynchronous). I've got this working fine. 

But now I want to add Views below the SortablePlayerTableView that will need to be updated depending on which row is clicked. I know I need to use addDataClickListener() for this. 

The problem is that SortableTableView draws over the top of Views below it. And I don't know how many rows will be returned, so I can't add a fixed dp either. 

Is there a simple way of ensuring Views below the SortableTableView will be visible?

**Comment by ISchwarz23** [comment]
Hi @mahye82,

sorry for the late respone. The issue here is the RelativeLayout. You have to set `android:layout_above="@id/tableView"` to the SortablePlayerTableView and swap the order of the SortablePlayerTableView and the TextView.

Best regards,
Ingo
