### ISSUE TITLE
Fixing first column with the header

### ISSUE THREAD

**Issue by dbshe** [ISchwarz23/SortableTableView#105]
Can we fix both first column as well first row(header)? I could achieve that using 2 table views for this table but now in my table I have many columns so I had to do it horizontally scrollable. Finding it difficult to achieve both horizontally and vertically scrollable table with fixed header row and column.

**Comment by ISchwarz23** [comment]
Hi @dbshe,

currently this feature is not supported by the library. This feature was not implemented on purpose, to keep the resulting apps as clean and as simple as possible.

Best regards,
Ingo

**Comment by dbshe** [comment]
Hi @ISchwarz23 

Thanks for the response, great work with the table view :)

Warm regards,
Darshan
