### ISSUE TITLE
How to change the color of text in a table ?

### ISSUE THREAD

**Issue by Vovusik** [ISchwarz23/SortableTableView#106]
I use day and night themes. Help me change the color of the text in the table.
Thanks.

**Comment by ISchwarz23** [comment]
Hi @Vovusik,

if you are using the `SimpleTableDataAdapter` just call the `setTextColor()` method. You just have to care to put the color value and not the color resource.

Best regards,
Ingo

**Comment by Vovusik** [comment]
Thank you very much for the help. But I need to use the color from the resource.

Example from the library:
Final SimpleTableHeaderAdapter simpleTableHeaderAdapter = new SimpleTableHeaderAdapter (context,
                 R.string ....);

SimpleTableHeaderAdapter.setTextColor (ContextCompat.getColor (context, R.color.colorWhite));
SetHeaderAdapter (simpleTableHeaderAdapter);

But using the SimpleTableDataAdapter

**Comment by ISchwarz23** [comment]
It is the same for the data adapter.
```
SimpleTableDataAdapter.setTextColor(ContextCompat.getColor(context, R.color.colorWhite));
```

**Comment by Vovusik** [comment]
I can not overcome this.
If you have the opportunity, help me, please. 
Thank you very much.

SimpleTableDataAdapter simpleTableDataAdapter = new SimpleTableDataAdapter(context, (List<String[]>) getContext());
        simpleTableDataAdapter.setTextColor(ContextCompat.getColor(context, R.color.colorAccent));
        setDataAdapter(simpleTableDataAdapter);

This example does not work.

**Comment by ISchwarz23** [comment]
I have checked if there is some regression, but the feature is working as expected. The code I used you can see here:

```java
final String[][] data = new String[][]{
            {"BMW", "3er", "120PS", "20.000€"}, 
            {"BMW", "4er", "130PS", "30.000€"}};

final SimpleTableDataAdapter dataAdapter = new SimpleTableDataAdapter(this, data);
dataAdapter.setTextColor(ContextCompat.getColor(this, R.color.table_data_text));

final TableView<String[]> tableView = (TableView) findViewById(R.id.tableView);
tableView.setDataAdapter(dataAdapter);
```

If this code is not working for you, the issue seems to be in another part of your application.

**Comment by aryst** [comment]
hye is there any way to just change the text color for specific row?
