### ISSUE TITLE
Refresh view does not provide an option to set new data i.e. ArrayList

### ISSUE THREAD

**Issue by kohlideepti** [ISchwarz23/SortableTableView#107]
Below is the example code I found on this project.  When I tried to carTableDataAdapter.clear() and carTableDataAdapter.addAll(Arrays.asList(Car[])) it did not work instead it threw me exception saying operation not permitted.  Is there any way to add new data when refreshed than just appending existing data?
-----
carTableView.setSwipeToRefreshListener(new SwipeToRefreshListener() {
                @Override
                public void onRefresh(final RefreshIndicator refreshIndicator) {
                    carTableView.postDelayed(new Runnable() {
                        @Override
                        public void run() {
                            final Car randomCar = getRandomCar();
                            carTableDataAdapter.getData().add(randomCar);
                            carTableDataAdapter.notifyDataSetChanged();
                            refreshIndicator.hide();
                            Toast.makeText(MainActivity.this, "Added: " + randomCar, Toast.LENGTH_SHORT).show();
                        }
                    }, 3000);
                }
            });

**Comment by ISchwarz23** [comment]
Could you please provide the Exception with StackTrace. Thanks!
