### ISSUE TITLE
Its possible to scroll horizontal too?

### ISSUE THREAD

**Issue by fernandodeveloper** [ISchwarz23/SortableTableView#109]
Its possible to scroll horizontal this table? or only vertical?

**Comment by SaeedZhiany** [comment]
yes, it's possible.

by searching in issues you can find various solutions, one of them that I test it and it's work fine is here:

put your `TableView` in a `HorizontalScrollView` and set the tableView's `width` to an appropriate value in `dp`. that's all.

just notice that you must not set the value to `wrap_content` or `match_parent`.

goodluck

**Comment by fernandodeveloper** [comment]
Both, too?

**Comment by SaeedZhiany** [comment]
with the above solution I have scroll in two direction. is that what you want?

**Comment by fernandodeveloper** [comment]
Yes. Because i have 8 columns with long content....

**Comment by SaeedZhiany** [comment]
happy coding :)
