### ISSUE TITLE
Maven Artifact of this library?

### ISSUE THREAD

**Issue by Luparion** [ISchwarz23/SortableTableView#11]
Hello Ingo,

can you please create a Maven Artifact of your library and deploy it to Maven Central? We want to use your library at work, however we use Maven as our build system and will not switch to Gradle in the near future.

Best Regards,
Luparion

**Comment by ISchwarz23** [comment]
Hey Luparion,
just as an information for me and as a new entry for the references: Can you tell me which company you are working for and where this company is located?
Best regards,
Ingo
Am 21.01.2016 22:26 schrieb Luparion <notifications@github.com>:Hello Ingo,

can you please create a Maven Artifact of your library and deploy it to Maven Central? We want to use your library at work, however we use Maven as our build system and will not switch to Gradle in the near future

Best Regards,
Luparion

**Comment by ISchwarz23** [comment]
Hi Luparion,

in the beginning I had the plan to publish this library also on Maven Central, but as JCenter is the default repository for Android libraries (and Maven Central has a pretty circumstantial way of releasing libraries) I decided not to do so.   
If you have a new idea in how I can support you and your company please let me know :)

Best regards,
Ingo

**Comment by ansshkki** [comment]
@ISchwarz23
Now, "JCenter is at end of life" as Android Studio tells us.
[https://developer.android.com/studio/build/jcenter-migration](https://developer.android.com/studio/build/jcenter-migration)
