### ISSUE TITLE
width and height ignored in adapters

### ISSUE THREAD

**Issue by SaeedZhiany** [ISchwarz23/SortableTableView#110]
I'm trying to use TableHeaderAdapter to create my custom header.

my table is here:

    <HorizontalScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <de.codecrafters.tableview.TableView
            android:id="@+id/feedingTable"
            android:layout_width="1000dp"
            android:layout_height="match_parent"
            table:tableView_columnCount="8" />
    </HorizontalScrollView>

and headers xml is:

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="60dp"
    android:layout_height="60dp"
    app:cardBackgroundColor="@color/feedingTableHeader"
    app:cardCornerRadius="0dp">

    <TextView
        android:id="@+id/cellTextView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:textColor="@color/mdtp_white" />
</android.support.v7.widget.CardView>
```

as you can see I set height and width to constant value that I need it. but when I run application it seems the width and height ignored and set library default values. is there any problem in my usage from library?

I'm using simple table view not the sortable one.

**Comment by ISchwarz23** [comment]
Hi @SaeedZhiany,

to avoid misusage of the library, the TableHeaderAdapter will override the LayoutParams of the cell view with the width provided by the column model and the height "wrap_content". So if you want your table header to contain CellViews with a height and width of 60dp you could use the following layout:
```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_widht="wrap_content"
    android:layout_height="wrap_content" >

    <android.support.v7.widget.CardView 
        android:layout_width="60dp"
        android:layout_height="60dp"
        app:cardBackgroundColor="@color/feedingTableHeader"
        app:cardCornerRadius="0dp">

        <TextView
            android:id="@+id/cellTextView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center"
            android:textColor="@color/mdtp_white" />

    </android.support.v7.widget.CardView>

</FrameLayout>
```

If you also want to have your columns having a width of 60dp you can use the `TableColumnDpWidthModel`.
```java
    TableView.setColumnModel(new TableColumnDpWidthModel(context, columnCount, 60));
```

**Comment by SaeedZhiany** [comment]
thank you for your great library and also your help
