### ISSUE TITLE
How to query whether a SortableTableView is in reverse sort order?

### ISSUE THREAD

**Issue by freefallmode** [ISchwarz23/SortableTableView#114]
This is a very helpful library, and I am close to fully implementing it in my project.

In the SortableTableView object which I am using, I wish to keep one particular row of data always at the top of the table, no matter which column is sorted.
I can force it to the top by adding a special case for that row in the column Comparator procedure, however, when reverse sorting, the row is sent to the last row of the table (the reverse ordering occurs after the Comparator sort).
Is there a way to query by which column the sortable tableview is sorted, and particularly, whether the relevant column is currently sorted in reverse order?

Additionally, how to disable the header row completely, or change it's view visibility to GONE?  In some cases I wish to display the table data without any headers.  Surely this must be simple?

Thanks for your help!

**Comment by ISchwarz23** [comment]
Hi @freefallmode,

till now the sort state is only available inside the TableView. There is no way to get it from outside.
Same applies to the header view. It is only manipulated by the TableView itself.
In both cases an extension of the api is needed. I can't promise a date when I'll implement this extension, but you are welcome to constribute to this library.

Best regards,
Ingo

**Comment by ISchwarz23** [comment]
Hi @freefallmode,

the version 2.7.0 was just released. This version provides the possibility to retrieve the sorting status of a sortable table using `SortableTableView#getSortingStatus()`. In addition there is the possibility to hide and show the table header using `TableView#setHeaderVisible( boolean )`. For more details about showing/hiding the header you can have a look at the [readme](https://github.com/ISchwarz23/SortableTableView#hide-table-header).

Best regards,
Ingo

**Comment by freefallmode** [comment]
Thanks for implementing these additions so quickly.
Query - is there an appropriate Listener for determining when a table sort has completed?

**Comment by ISchwarz23** [comment]
Would it be sufficient to have the possibility to listen for `SortingStatus` changes?

**Comment by freefallmode** [comment]
I think so, providing that the SortingStatus change listener occurs after all the table elements have been sorted/updated.

**Comment by freefallmode** [comment]
Just an idea.. A listener for table row changes could also prove useful to people. E.g. if one wanted to update a field with the total number of data rows automatically every time the underlying array changes (add, remove, clear etc) (I am achieving this by alternative means).

**Comment by ISchwarz23** [comment]
Hi @freefallmode,

the SortableTableView in version 2.8.0 supports the registering of a `SortingStatusChangeListener`.
For new ideas please create a new issue, so it is more easy to track and discuss them :)

Best regards,
Ingo

**Comment by freefallmode** [comment]
Good work, and many thanks!

I'll create new feature requests as you suggest.

Simon

On Sep 1, 2017 02:19, "Ingo Schwarz" <notifications@github.com> wrote:

Hi @freefallmode <https://github.com/freefallmode>,

the SortableTableView in version 2.8.0 supports the registering of a
SortingStatusChangeListener.
For new ideas please create a new issue, so it is more easy to track and
discuss them :)

Best regards,
Ingo

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ISchwarz23/SortableTableView/issues/114#issuecomment-326348035>,
or mute the thread
