### ISSUE TITLE
Example of Adding Header Data

### ISSUE THREAD

**Issue by DivisionMax** [ISchwarz23/SortableTableView#115]
Firstly, thanks for the library. An example of adding header data in the README would be useful, even a simple one
E.g. 
``` java
private final String[] tableHeaders = {"A", "B", "C", "D"};
@Override
protected void onCreate(Bundle savedInstanceState) {
...
    tableView.setHeaderAdapter(new SimpleTableHeaderAdapter(this, tableHeaders))
...
}
```

It was not super obvious for me, it would help newbies.

**Comment by ISchwarz23** [comment]
Hi @DivisionMax,

the [HeaderData section](https://github.com/ISchwarz23/SortableTableView/#header-data) was extended with an example about how to show plain strings and strings from resources inside the table header. 

Best regards,
Ingo
