### ISSUE TITLE
Sort nulls last?

### ISSUE THREAD

**Issue by 10erlosh** [ISchwarz23/SortableTableView#116]
Hi,
thanks for this great lib!
Is there a way to have NULL values sorted last regardless of the `SortingOrder`?

**Comment by ISchwarz23** [comment]
Hi @10erlosh,

yes, you could implement a comparator that is respecting the SortingOrder. Depending on this SortingOrder you can make NULL the first items or the last items so they will always be last inside the view.

Best regards,
Ingo

**Comment by 10erlosh** [comment]
Sorry for late response.
Could you provide an example?
My column comparators are set in ctor of the TableView:
`setColumnComparator(COL_NAME, SomeModel.getNameComparator());`

**Comment by ISchwarz23** [comment]
Hi @10erlosh,

find below an example for a Comparator that will sort the Cars which have "null" values for their names will be sorted last. As I did this example just for you, it would be nice if you could support his project (e.g. by constribution or donation). But anyway, here the example :)

```
public class CarNameComparator implements Comparator<Car> {

    private final SortingStatus sortingStatus;
    private final int columnIndex;

    private CarNameComparator(final SortingStatus sortingStatus, final int columnIndex) {
        this.sortingStatus = sortingStatus;
        this.columnIndex = columnIndex;
    }

    @Override
    public int compare(final Car car1, final Car car2) {

        if (car1.getName() == null) {
            if (sortingStatus.getSortedColumnIndex() == 1 &&
                    sortingStatus.getSortedOrder() == SortingOrder.ASCENDING) {
                return 1;
            } else {
                return -1;
            }
        }
        if (car2.getName() == null) {
            if (sortingStatus.getSortedColumnIndex() == 1 &&
                    sortingStatus.getSortedOrder() == SortingOrder.ASCENDING) {
                return -1;
            } else {
                return 1;
            }
        }
        return car1.getName().compareTo(car2.getName());
    }
 }
```

Use it like this:
```
sortableTableView.setColumnComparator( 1, new CarNameComparator(sortableTableView.getSortingStatus(), 1) );
```
