### ISSUE TITLE
Only show one row in Custom TableDataAdapter

### ISSUE THREAD

**Issue by immosk** [ISchwarz23/SortableTableView#118]
Hi @ISchwarz23 , 
I have a little problem with my data in my tableview. I have some data (JSON) from public API. I create a custom Adapter implements of TableDataAdapter like documentation said but only one row which show. I dont know `count` or something who handle the length of row work but I love to know. Below my snippet code : 

TableViewAdapter.kt
`class TableViewAdapter(context: Context, data:List<JSONArray>, tableView: SortableTableView<JSONArray>): TableDataAdapter<JSONArray>(context, data) {
    override fun getCellView(rowIndex:Int, columnIndex:Int, parentView: ViewGroup): View? {
        val data = getRowData(rowIndex)

        var renderedView: View? = null

        when (columnIndex) {
            0 -> renderedView = renderTitleName(data, rowIndex, columnIndex)
        //            0 -> Log.d("data" , "" + count)
            1 -> renderedView = renderTitleName(data, rowIndex, columnIndex)
            2 -> renderedView = renderTitleName(data, rowIndex, columnIndex)
            3 -> renderedView = renderTitleName(data, rowIndex, columnIndex)
            4 -> renderedView = renderTitleName(data, rowIndex, columnIndex)

        }
        return renderedView
    }

    fun renderTitleName(data: JSONArray, rowIndex: Int, columnIndex: Int): View {
        val textView = TextView(context)
        textView.textSize = 14f
        textView.setPadding(20, 20, 20, 20)

        var dataRow = data[rowIndex] as JSONObject

        if (columnIndex == 0) {
            textView.text = dataRow.getString("title")
        } else if (columnIndex == 1) {
            textView.text = dataRow.getString("id")
        } else if (columnIndex == 2) {
            textView.text = dataRow.getDouble("popularity").toString()
        } else if (columnIndex == 3) {
            textView.text = dataRow.getString("release_date")
        } else if (columnIndex == 4) {
            textView.text = dataRow.getString("vote_count")
        }
        return textView
    }
    }`

And here I use the Adapter : 
MainActivity.kt

        `tableViewAdapter = TableViewAdapter(this, listOf(dataArrayResponse), tableview!!)
         tableview?.dataAdapter = tableViewAdapter
         tableViewAdapter?.notifyDataSetChanged()`

I using Kotlin , do I do a mistake? Any suggest will help for me. Thanks in Advance

**Comment by ISchwarz23** [comment]
Hi @immosk,

I guess in your case it is not an issue of the adapter. Could you please post your layout.

Best regards,
Ingo

**Comment by immosk** [comment]
Hi @ISchwarz23 , 
Here my activity xml : 
`<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <HorizontalScrollView
        android:layout_width="0dp"
        android:layout_height="match_parent" >

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <de.codecrafters.tableview.SortableTableView
                android:id="@+id/tableView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:tableView_headerColor="@color/colorPrimary"
                app:tableView_headerElevation="1"
                app:tableView_columnCount="5" />
        </LinearLayout>
    </HorizontalScrollView>

    </android.support.constraint.ConstraintLayout>
`

**Comment by immosk** [comment]
Hi @ISchwarz23 , 

I think I do a mistake with my adapter. I test in Java with : 

    public class TableViewAdapter extends TableDataAdapter<JSONObject> {
    public TableViewAdapter(Context context, ArrayList data) {
        super(context, data);
    }
    public class TableViewAdapter extends TableDataAdapter<JSONObject> {
    public TableViewAdapter(Context context, ArrayList data) {
        super(context, data);
    }

instead 

    public class TableViewAdapter extends TableDataAdapter<JSONArray> {
    public TableViewAdapter(Context context, JSONArray[] data) {
        super(context, data);
    }

And its work now. I think I should throw the data with object type like Any, String, or etc CMIIW (not Array/JSONArray) . Now its fine. Thanks for your response .
