### ISSUE TITLE
Unable to load rows of data

### ISSUE THREAD

**Issue by PSLDev94** [ISchwarz23/SortableTableView#121]
Hi,

I am using the custom data method for rows. After initialising and calling my DataAdapter, the constructor is executed but not the getCellView overriding method. I believe this is why the rows with data are not loaded. I'm really not sure why this is happening.

So while debugging, I notice my that the data is successfully passed to the constructor but after that nothing happens. 

Here is how I'm initialising and calling the adapters (usersList is an ArrayList of objects):

`        final TableView<Users> GlobalTable = (TableView<Users>) getView().findViewById(R.id.global_tableview);`

`                    final TableDataAdapter tableDataAdapter = new TableDataAdapter(getActivity(), usersList);
                    GlobalTable.setDataAdapter(tableDataAdapter);`

Then my table data adapter is identical to your custom adapter example 

Thanks

**Comment by shubhamnandanwar** [comment]
I am facing the same problem.

**Comment by ISchwarz23** [comment]
Hi,

I wonder how you can create an instance of the TableDataAdapter as it is abstract.
I also recommend to add a generic (like User) to the TableDataAdapter.

Best regards,
Ingo

**Comment by AnishGG** [comment]
Hi, I am facing the same issue.

**Comment by ISchwarz23** [comment]
May I see some of your code?

**Comment by AnishGG** [comment]
Hello, Below are the classes in which I am facing this issue.
getCellView() method is never called. 
public class tableText {
        private final String[] text = new String[9];
        private int flagi, counti;
        public tableText() {
        }
        public void setString(String s, int idx) {
            text[idx] = s;
        }
        public void setFlagi(int flag) {
            flagi = flag;
        }
        public void setCounti(int count) {
            counti = count;
        }
        public String getString(int idx) {
            return text[idx];
        }
        public int getFlag() {
            return flagi;
        }
        public int getCount() {
            return counti;
        }
    }

public class ReportTableDataAdapter extends TableDataAdapter<TripReport.tableText> {
    private static final int TEXT_SIZE = 14;

    public ReportTableDataAdapter(final Context mycontext, final List<TripReport.tableText> mytrip) {
        super(mycontext, mytrip);
    }

    @Override
    public View getCellView(int rowIndex, int columnIndex, ViewGroup parentView) {
        final TripReport.tableText tableText = getRowData(rowIndex);
        Log.d("hello", rowIndex+" " + columnIndex);
        return getDataTextView(tableText, columnIndex);
    }

    private View getDataTextView(TripReport.tableText tableText, int j){
        String data = tableText.getString(j);
        Log.d("mydata", data);
        final TextView textView = new TextView(getContext());
        textView.setText(data);
        textView.setPadding(20, 10, 20, 10);
        textView.setTextSize(TEXT_SIZE);
        textView.setTextColor(getResources().getColor(de.codecrafters.tableview.R.color.primary_dark_material_dark));
        textView.setSingleLine();
        return textView;
    }
}

Above is the ReportTableDataAdapter class, which I am using as:
sortableTripTable.setDataAdapter(new ReportTableDataAdapter(getContext(), trip));

Where sortableTripTable is a custom class:
public class SortableTripTable extends SortableTableView<TripReport.tableText>{};

**Comment by ISchwarz23** [comment]
What is `ReportTableDataAdapter#getCount()` return?

**Comment by AnishGG** [comment]
It returns the private variable counti. (Class is used somewhere else also)

**Comment by ISchwarz23** [comment]
I'm talking about the class `ReportTableDataAdapter` not `tableText`. Is it returning the same value?

**Comment by AnishGG** [comment]
Could you explain what are you asking? 
Are you asking the value of getCount() method after creating an instance of ReportTableDataAdapter?
That is returning the 'number of instances of tableText' that are present in the trip(list).

**Comment by AnishGG** [comment]
If it helps, here is the SortableTripTable class:
`public class SortableTripTable extends SortableTableView<TripReport.tableText> {
    public SortableTripTable(final Context context){
        this(context, null);
    }

    public SortableTripTable(final Context context, final AttributeSet attributes){
        this(context, attributes, android.R.attr.listViewStyle);
    }

    public SortableTripTable(final Context context, final AttributeSet attributes, final int styleAttributes){
        super(context, attributes, styleAttributes);
        final SimpleTableHeaderAdapter simpleTableHeaderAdapter = new SimpleTableHeaderAdapter(context, "somevalue", "somevalue", "somevalue", "somevalue", "somevalue", "somevalue", "somevalue", "somevalue", "somevalue");
        simpleTableHeaderAdapter.setTextColor(ContextCompat.getColor(context, R.color.table_header_text));
        simpleTableHeaderAdapter.setTextSize(15);
        setHeaderAdapter(simpleTableHeaderAdapter);
        final int rowColorEven = ContextCompat.getColor(context, R.color.table_data_row_even);
        final int rowColorOdd = ContextCompat.getColor(context, R.color.table_data_row_odd);
        setDataRowBackgroundProvider(TableDataRowBackgroundProviders.alternatingRowColors(rowColorEven, rowColorOdd));
        setHeaderSortStateViewProvider(SortStateViewProviders.brightArrows());

        TableColumnDpWidthModel columnModel = new TableColumnDpWidthModel(context, 9, 200);
        columnModel.setColumnWidth(0, 50);
        columnModel.setColumnWidth(1, 200);
        columnModel.setColumnWidth(2, 200);
        columnModel.setColumnWidth(3, 200);
        columnModel.setColumnWidth(4, 200);
        columnModel.setColumnWidth(5, 200);
        columnModel.setColumnWidth(6, 200);
        columnModel.setColumnWidth(7, 200);
        columnModel.setColumnWidth(8, 200);
        setColumnModel(columnModel);

        setColumnComparator(2, new compareme(2));
        setColumnComparator(3, new compareme(3));
    }

    private static class compareme implements Comparator<TripReport.tableText>{
        private int i;
        public compareme(int idx){i = idx;}
        @Override
        public int compare(final TripReport.tableText t1, final TripReport.tableText t2){
            return t1.getString(i).compareTo(t2.getString(i));
        }
    }
}
`

**Comment by ISchwarz23** [comment]
Looks good. Maybe you show me the layout file which contains the SortableTripTable?!

**Comment by AnishGG** [comment]
Here's the layout file:
`        <Somename.SortableTables.SortableTripTable
            android:id="@+id/sortableTrip"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
        </Somename.SortableTables.SortableTripTable>`

and I use the adapter as follows:
`sortableTripTable = (SortableTripTable) view.findViewById(R.id.sortableTrip);
reportTableDataAdapter = new ReportTableDataAdapter(getContext(), trip);
sortableTripTable.setDataAdapter(reportTableDataAdapter);`

Is any column adapter necessary to add as per your example app? Or only the above will suffice?

**Comment by ISchwarz23** [comment]
The code you provided should already show your data inside a table. The table will use a default table model (all columns have eual width).

Is the "trip"-list already filled when you run this code, or is it filled in a later point in time.

**Comment by AnishGG** [comment]
It is filled in runtime but before the declaration of reportTableDataAdapter.

**Comment by ISchwarz23** [comment]
Very strange. I guess I can't help here any more without doing some debugging of your code.

I just can give you the following hints:
- make sure the table is hight enough to show the data section
- make sure you notify the DataAdapter anytime you manipulate the data (by calling TableDataAdapter#notifyDataSetChanged())
- make sure the TableDataAdapter returns a number bigger than 0 when calling TableDataAdapter#getCount() (this can be the case, if you use special implementations of List e.g. JsonArray)

**Comment by AnishGG** [comment]
Voila!!!
Just resolved the issue.
The problem was with the scrollable view in the xml file.
I was using scrollable view for the table, but it is already provided by your library. So by just removing the scrollable view, it resolved the issue.
Thanks!

**Comment by ISchwarz23** [comment]
Very nice! I'm happy that the library is now also Wirkung in your project. :-)
