### ISSUE TITLE
Set a selected row

### ISSUE THREAD

**Issue by derleiLisboa** [ISchwarz23/SortableTableView#124]
How to select a row? I need load a list and set a item as default.

**Comment by ISchwarz23** [comment]
Hi @derlwiLisboa,

unfortunately selection is not supported by this library. But there is a new generation of this library available at [sortabletableview.com](http://www.sortabletableview.com), which support the selection feature and much more new features. This new library is based on the recycler view, so it uses up to date technology which enables better performance.

Best regards,
Ingo

**Comment by derleiLisboa** [comment]
Ok, thanks for attention..
And congratulations for your work!

Best regards,
Derlei
