### ISSUE TITLE
Horizontal scrolling issue

### ISSUE THREAD

**Issue by Pitel** [ISchwarz23/SortableTableView#126]
I've the following layout with wide table (using `TableColumnDpWidthModel`):

```xml
<HorizontalScrollView
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	android:fillViewport="true"
	android:nestedScrollingEnabled="true">

	<de.codecrafters.tableview.SortableTableView
		android:id="@+id/table"
		android:layout_width="wrap_content"
		android:layout_height="match_parent"
		app:tableView_columnCount="11" />
</HorizontalScrollView>
```

And it doesn't work as expected:
1. There is no scrolling inertia (scrolling stops immediately after lifting finger from screen).
2. It doesn't scroll horizontaly.

**Comment by Pitel** [comment]
The inertia was solved by moving `android:nestedScrollingEnabled` to `SortableTableView`.

But I still can't scroll horizontaly.

**Comment by Pitel** [comment]
Setting table's `layout_width` to fixed value in dp makes the scrolling works as expected, but I'd prefere to let the table itself decide how wide it wants to be.

**Comment by ISchwarz23** [comment]
Unfortunatelly this is not supported.
