### ISSUE TITLE
Is it possible to have frozen columns as you scroll horizontally?

### ISSUE THREAD

**Issue by dummyjaysel** [ISchwarz23/SortableTableView#127]
Hi! Just want to know if it is possible to have freeze columns as you scroll horizontally in your table?  Thank you so much. God bless.

**Comment by ISchwarz23** [comment]
Hi @dummyjaysel,

no, unfortunately the library does not provide this functionality.

Best regards,
Ingo

**Comment by immosk** [comment]
Waiting for this update
