### ISSUE TITLE
Only shows 1 row when used in a listview.

### ISSUE THREAD

**Issue by yigitserin** [ISchwarz23/SortableTableView#13]
Hi there,

I am trying to implement this TableView in a ListView. The problem is, it only shows 1 row and you have to scroll the tableview itself to see other rows. Is it a bug or am I doing something wrong? Here is what I do:

This is my JSON data:

`{"Rows":[{"Column":["Karşıyaka-Bornova","Bornova-Karşıyaka"]},{"Column":["9:30","10:00"]},{"Column":["10:30","11:00"]}]}
`

Code:

```Java
LinearLayout.LayoutParams params2 = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.MATCH_PARENT);
            
JSONObject table = new JSONObject(s10Data);
int columns = table.getJSONArray("Rows").getJSONObject(0).getJSONArray("Column").length();
int rows = table.getJSONArray("Rows").length();
List<String[]> tableList = new ArrayList<>();
TableView<String[]> tableView = new TableView(activity);
tableView.setColumnCount(columns);


for (int j = 0; j < rows; j++) {
    String[] rowItems = new String[columns];
         for (int k = 0; k < columns; k++) {
               rowItems[k] = table.getJSONArray("Rows").getJSONObject(j).getJSONArray("Column").getString(k);
                }
                tableList.add(rowItems);
           }

SimpleTableDataAdapter adapter10 = new SimpleTableDataAdapter(activity,tableList);
tableView.setDataAdapter(adapter10);
tableView.setLayoutParams(params2);
holder.innerLinearLayout.addView(tableView);
```

And this is what happens:

[Picture](http://i.imgur.com/nm8kz2S.png)

This is how it supposed to appear. (Have no idea why there is grey space on it)

[Picture](http://i.imgur.com/buGUoMm.png)

Edit:
After implementing a headeradapter, it now shows header and 1 other row. Still need a solution here.

**Comment by ISchwarz23** [comment]
Hi yigitserin,   
you wrote that you want to add the TableView in a ListView, but in your code you are adding it to a LinearLayout, right?   
As I unfortunately do not exactly know how your result should look like (full scope of the activity) it would be really nice, if you can describe that here. And then we could think about a layout that makes that feasible and I can show you how the TableView was intended to be used in your use-case.   
Looking forward hearing from you! :)

**Comment by yigitserin** [comment]
Yeah it is a linearlayout in a tableview. This code is actually is in a getview method of baseadapter for a listview. 

I will give more details when i get to home.

**Comment by yigitserin** [comment]
So I have a ListView which is controlled by a BaseAdapter.

Each ListView item have a LinearLayout in it. Each LinearLayout have a bunch of items, including the TableView.

These items are created dynamically, but when I create the TableView, it only shows 1 header row and 1 data row. However when I scroll the TableView, it scrolls down to other data.

So how do I make it wrap all the data?

**Comment by yigitserin** [comment]
Fixed this issue by giving a static height instead of wrap_content.
