### ISSUE TITLE
How to setVisibility of custom Layout for only one row in SortableTableView Android?

### ISSUE THREAD

**Issue by nikolabozicbg** [ISchwarz23/SortableTableView#130]
I have full question here: https://stackoverflow.com/questions/47613816/how-to-setvisibility-of-custom-layout-for-only-one-row-in-sortabletableview-andr

Can you help me please mister?

**Comment by ISchwarz23** [comment]
Hi @nikolabozicbg,

I'm not completely sure that I understood your issue. Could you please tell me what you are trying to achive, e.g. with a mockup and I will provide an example implementation for it, if it is feasible.

Best regards,
Ingo

**Comment by nikolabozicbg** [comment]
Hi sir i have made custom layout for every row. In that layout i have layout with icon buttons that is set on invisible. What i want is when user click on certain row to change layout with buttons to visible.  I achieve that, but still i have problem that layout with buttons is is show for each row  in the order that the user click, and not only the selected row. Workflow that i would like  when  user click one row , two buttons(for edit and delete) pop out(that layout is set to visible), and when user click on another row , buttons from previous row disappear and pop up on row that user clicked.
Here is my code:

public class FragmentTableUsers extends Fragment {
View v;   
ArrayList<User> allUsers;   
private static final String[] TABLE_HEADERS = { "Ime", "Prezime"};

public FragmentTableUsers() {       
}

@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container,
                         Bundle savedInstanceState) {
    DataBaseHelper helper = new DataBaseHelper(getActivity());
    allUsers = helper.getAllUsers();

    v =  inflater.inflate(R.layout.fragment_fragment_add_user, container, false);

    TableView tableView = (TableView<String[]>) v.findViewById(R.id.tableView);
    tableView.setColumnCount(2);
    tableView.setDataAdapter(new UserTableDataAdapter(getActivity(), allUsers, v, inflater, tableView));
    SimpleTableHeaderAdapter simpleHeader = new SimpleTableHeaderAdapter(getActivity(), TABLE_HEADERS);
    simpleHeader.setTextColor(Color.WHITE);
    simpleHeader.setPaddingTop(8);
    simpleHeader.setPaddingBottom(8);

    tableView.setHeaderAdapter(simpleHeader);
    tableView.setHeaderElevation(10);
    int colorEvenRows = getResources().getColor(R.color.white);
    int colorOddRows = getResources().getColor(R.color.et_grey);
    tableView.setDataRowBackgroundProvider(TableDataRowBackgroundProviders.alternatingRowColors(colorEvenRows, colorOddRows));      

    ImageButton button = (ImageButton) v.findViewById(R.id.addbuton);
    button.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            FragmentAddEditUsers fragmentAddEditUsers = new FragmentAddEditUsers();
            FragmentManager fragmentManager = getActivity().getSupportFragmentManager();
            FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
            fragmentAddEditUsers.setTargetFragment(FragmentTableUsers.this, 1);
            fragmentTransaction.replace(R.id.layoutForFragments, fragmentAddEditUsers, "1");
            fragmentTransaction.addToBackStack("1");
            fragmentTransaction.commit();
        }
    });
    return  v;
} 

class UserTableDataAdapter extends TableDataAdapter<User> {
View v;
View addEditIcons;
LayoutInflater inflater;
TableView tableView;

public UserTableDataAdapter(Context context, List<User> data, View v, LayoutInflater inflate, TableView tableView) { // HERE I INITIALIZE CUSTOM VIEW
    super(context, data);
    this.inflater = inflate;
    this.v = v;
    this.tableView = tableView;
}

@Override
public View getCellView(int rowIndex, int columnIndex, ViewGroup  parentView) {
    addEditIcons = inflater.inflate(R.layout.add_edit_icons,parentView , false);
    User user = getRowData(rowIndex);
    tableView.invalidate();

    switch (columnIndex) {
        case 0:
            addEditIcons = showLayout(user);
            break;
    }
    return addEditIcons;
}

private View showLayout (final User user) {
    final LinearLayout iconsLayout = addEditIcons.findViewById(R.id.iconsLayout);
    LinearLayout mainlayout = addEditIcons.findViewById(R.id.mainAddEditIcons);
    mainlayout.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            iconsLayout.setVisibility(View.VISIBLE);
        }
    });

    TextView tvRow = addEditIcons.findViewById(R.id.tvRow);
    tvRow.setText(user.getSurname().toString());
    return mainlayout;
}

XML for every row clicked:
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/mainAddEditIcons"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:visibility="visible">

    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:orientation="vertical">

        <LinearLayout
            android:id="@+id/iconsLayout"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:orientation="horizontal"
            android:visibility="invisible">

            <ImageButton
                android:id="@+id/imageButton"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                app:srcCompat="@android:drawable/ic_input_add" />

            <ImageButton
                android:id="@+id/imageButton2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                app:srcCompat="@android:drawable/ic_menu_edit" />

        </LinearLayout>

        <LinearLayout
            android:id="@+id/tvLAyout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:orientation="vertical">

            <TextView
                android:id="@+id/tvRow"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_weight="1" />
        </LinearLayout>

    </LinearLayout>

</LinearLayout>

Here is printscreen: 
https://ibb.co/e508hw

You can see in picture that both rows have icons , and not only selected one.
Thanks in advance.

**Comment by ISchwarz23** [comment]
I would recommend to add a boolean property (e.g. "isEditable") to your User class. This property is checked by the Adapter to know if the buttons shall be available or not.
```java
private View showLayout (final User user) {
    final LinearLayout iconsLayout = addEditIcons.findViewById(R.id.iconsLayout);
    LinearLayout mainlayout = addEditIcons.findViewById(R.id.mainAddEditIcons);
    LinearLayout tvLayout = addEditIcons.findViewById(R.id.tableViewLaayout);
    if( user.isEditable() ) {
        iconsLayout.setVisibility(View.VISIBLE); 
    } else {
        iconsLayout.setVisibility(View.GONE); 
    }
    TextView tvRow = addEditIcons.findViewById(R.id.tvRow);
    tvRow.setText(user.getSurname().toString());
    return mainlayout;
}
```

The property is managed by a TableDataClickListener:
```java
public class UserEditableOnClickListener implements TableDataClickListener<User> {

    private final TableDataAdapter<User> adapter;
    
    public UserEditableOnClickListener(TableDataAdapter<User> adapter) {
        this.adapter = adapter;
    }

    @Override
    public void onDataClicked(int rowIndex, User clickedUser) {
        // make all users non-editable
        for( User user : adapter.getData() ) {
            user.setEditable( false );
        }
        // make the clicked user editable
        clickedUser.setEditable( true );
        // trigger new rendering
        adapter.notifyDataSetChanged();
    }
}
```

Hope this matches your expectations.

**Comment by nikolabozicbg** [comment]
What adapter should i pass in this line:
 tableView.addDataClickListener(new UserEditableOnClickListener()); ?

**Comment by nikolabozicbg** [comment]
That is exactly what i was looking for! Thanks for help and great library.
 Best regards.
