### ISSUE TITLE
Is it posible to show floating action button between rows, when user click one row?

### ISSUE THREAD

**Issue by nikolabozicbg** [ISchwarz23/SortableTableView#134]
Hi sir, Its me again. I have made custom layout for every row, and in that layout i have floating action button. What i want is when user click on row to popup floating action button overlapping two rows. Problem i when action button pops up it is cut inside width of one row , and don't overlap between two rows.

Here is my code:

     @Override
     public void onEventLongPress(WeekViewEvent event, RectF eventRect) {
     allEventsWithDate =  helper.getEventsWithDate(sdf.format(event.getStartTime().getTime()));

     final Dialog dialog = new Dialog(getContext());
     dialog.setContentView(R.layout.table_inevent);
     dialog.getWindow().setLayout(WindowManager.LayoutParams.MATCH_PARENT, 
     WindowManager.LayoutParams.MATCH_PARENT);
     dialog.show();

     tableView = (TableView<String[]>) dialog.findViewById(R.id.tableView);
     adapter = new EventeDataAdapter(getActivity(), allEventsWithDate, v, getLayoutInflater(), 
     tableView);
     tableView.setColumnCount(5);
     tableView.setDataAdapter(adapter);
     SimpleTableHeaderAdapter simpleHeader = new SimpleTableHeaderAdapter(getActivity(), TABLE_HEADERS);
     simpleHeader.setTextColor(Color.WHITE);
     tableView.setHeaderAdapter(simpleHeader);
     tableView.setHeaderElevation(10);
     simpleHeader.setTextColor(Color.WHITE);
     simpleHeader.setPaddingTop(8);
     simpleHeader.setPaddingBottom(8);
     int colorEvenRows = getResources().getColor(R.color.white);
     int colorOddRows = getResources().getColor(R.color.et_grey);       
  
    tableView.setDataRowBackgroundProvider(TableDataRowBackgroundProviders.alternatingRowColors
    (colorEvenRows, colorOddRows));
      tableView.addDataClickListener(new EventOnClickListener(adapter, allEventsWithDate));
 }

    public class EventOnClickListener implements TableDataClickListener<EventGui> {
    private TableDataAdapter<EventGui> adapter;
    private ArrayList<EventGui> list;
    public EventOnClickListener(TableDataAdapter<EventGui> adapter, ArrayList<EventGui> list) {
          this.adapter = adapter;
          this.list = list;
     }

        @Override
       public void onDataClicked(int rowIndex, EventGui clickedEvent) {
            for( EventGui eventGui : list ) {
                System.out.println("u for");
                eventGui.setSeleted(false);
            }
            clickedEvent.setSeleted( true );
            System.out.println("u kliku" + clickedEvent.isSeleted());
            adapter.notifyDataSetChanged();
        }
    }

    class EventeDataAdapter extends TableDataAdapter<EventGui> {
    View v;
    View addEditIcons;
    LayoutInflater inflater;
    TableView tableView;
    List<EventGui> data;

    @Override
    public List<EventGui> getData() {
        return data;
    }

    public void setData(List<EventGui> data) {
        this.data = data;
    }

    public EventeDataAdapter(Context context, List<EventGui> data, View v, LayoutInflater inflater, TableView tableView) { 
        super(context, data);
        this.inflater = inflater;
        this.v = v;
        this.tableView = tableView;
    }

    @Override
    public View getCellView(int rowIndex, int columnIndex, ViewGroup  parentView) {
        addEditIcons = inflater.inflate(R.layout.add_edit_icons,parentView , false);
        EventGui event = getRowData(rowIndex);

        switch (columnIndex) {
            case 0:
               addEditIcons = showStartTime(event);
                break;
            case 1:
                addEditIcons = showEndTime(event);
                break;
            case 2:
                addEditIcons = showPatient(event);
                break;
            case 3:
                addEditIcons = showDoctor(event);
                break;
            case 4:
                addEditIcons = showCheckUpType(event);
                break;

        }
        return addEditIcons;
    }

    private View showStartTime(final EventGui eventGui) {

        CoordinatorLayout mainlayout =(CoordinatorLayout) addEditIcons.findViewById(R.id.mainlayout);
        android.support.design.widget.FloatingActionButton fab =  (android.support.design.widget.FloatingActionButton) addEditIcons.findViewById(R.id.fab);
        fab.setVisibility(addEditIcons.GONE);
        TextView tvRow = addEditIcons.findViewById(R.id.tvRow);
        tvRow.setText(eventGui.getStarTime().toString());
        return mainlayout;
    }

    private View showEndTime(final EventGui eventGui) {
        CoordinatorLayout mainlayout =(CoordinatorLayout) addEditIcons.findViewById(R.id.mainlayout);
        android.support.design.widget.FloatingActionButton fab =  (android.support.design.widget.FloatingActionButton) addEditIcons.findViewById(R.id.fab);
        fab.setVisibility(addEditIcons.GONE);
        TextView tvRow = addEditIcons.findViewById(R.id.tvRow);
        tvRow.setText(eventGui.getEndTime().toString());
        return mainlayout;
    }

    private View showPatient(final EventGui eventGui) {
        CoordinatorLayout mainlayout =(CoordinatorLayout) addEditIcons.findViewById(R.id.mainlayout);
        android.support.design.widget.FloatingActionButton fab =  (android.support.design.widget.FloatingActionButton) addEditIcons.findViewById(R.id.fab);
        fab.setVisibility(addEditIcons.GONE);
        TextView tvRow = addEditIcons.findViewById(R.id.tvRow);
        tvRow.setText(eventGui.getPatientName().toString() + " " +  eventGui.getPatientSurName().toString());
        return mainlayout;
    }

    private View showDoctor(final EventGui eventGui) {
        CoordinatorLayout mainlayout =(CoordinatorLayout) addEditIcons.findViewById(R.id.mainlayout);
        android.support.design.widget.FloatingActionButton fab =  (android.support.design.widget.FloatingActionButton) addEditIcons.findViewById(R.id.fab);
        fab.setVisibility(addEditIcons.GONE);
        TextView tvRow = addEditIcons.findViewById(R.id.tvRow);
        tvRow.setText(eventGui.getUserName());
        return mainlayout;
    }

    private View showCheckUpType(final EventGui eventGui) {
        CoordinatorLayout mainlayout =(CoordinatorLayout) addEditIcons.findViewById(R.id.mainlayout);
        android.support.design.widget.FloatingActionButton fab =  (android.support.design.widget.FloatingActionButton) addEditIcons.findViewById(R.id.fab);

        TextView tvRow = addEditIcons.findViewById(R.id.tvRow);

        if(eventGui.isSeleted()) {
            fab.setVisibility(addEditIcons.VISIBLE);
        } else {
            fab.setVisibility(addEditIcons.GONE);
        }
        tvRow.setText(eventGui.getChekupType());
        return mainlayout;
    }
}

Layout of one row:

    <android.support.design.widget.CoordinatorLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/mainlayout"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_marginTop="-10dp"
        android:clickable="true"
        android:src="@drawable/fab_add"
        app:layout_anchor="@id/viewA"
        app:layout_anchorGravity="bottom|right|end" />

    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <LinearLayout
            android:id="@+id/viewA"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_weight="0.6"
            android:orientation="horizontal">

            <TextView
                android:id="@+id/tvRow"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:gravity="left"
                android:text="NILU" />
        </LinearLayout>

    </LinearLayout>

</android.support.design.widget.CoordinatorLayout>

Here is the output:

https://ibb.co/eqZf4m

What i would like is something like : 

https://ibb.co/gerPx6

**Comment by ISchwarz23** [comment]
Could you explain in more detail how the result should look like? It would be even better if you could provide some mockups.

**Comment by nikolabozicbg** [comment]
Please look update sir.

**Comment by nikolabozicbg** [comment]
Any ideas how to accomplish this sir?

**Comment by ISchwarz23** [comment]
Hi @nikolabozicbg,

no, unfortuntalley not, as something like this was never foreseen.
I would just go for a different solution. I would have the floating button (as described in the Android style guide) and the bottom right corner. But the context (meaning the data object) for which the actions are trigged are related to the user selection.

Best regards,
Ingo
