### ISSUE TITLE
How to limit number of rows

### ISSUE THREAD

**Issue by c0dehunter** [ISchwarz23/SortableTableView#135]
How can I limit the number of rows? I have a dataset of about 1000 items and I am displaying it in SortableTableView. Dataset can be sorted by 3 fields so I need to have the full set but I want the user to be able to see only first 10 (based on current sorting).

**Comment by ISchwarz23** [comment]
Hi @c0dehunter,
you can override the `getCount()` method of the `TableDataAdapter` and return 10 if the `super.getCount()` returns more than 10.
Best regards,
Ingo

**Comment by c0dehunter** [comment]
Wow this was easy. Thank you!
