### ISSUE TITLE
How to set Background Row Color

### ISSUE THREAD

**Issue by aryst** [ISchwarz23/SortableTableView#138]
Hye i have tried day and night just to change the background color for just some specific row but still haven't find the way. Please help me

**Comment by ISchwarz23** [comment]
Hi @aryst,

Have you tried the `TableDataRowBackgroundProvider`? Using this provider you can set a background drawable depending on row index or row data.

Best regards,
Ingo

**Comment by aryst** [comment]
ya i have tried the TableDataRowBackgroundProvider but how to just highlighted specific row?

**Comment by ISchwarz23** [comment]
What is the special property of this row? Should it be highlighted because of its index or because it contains data with a certain property?

**Comment by aryst** [comment]
it  should be highlighted because it contains data with a certain property

**Comment by ISchwarz23** [comment]
So you can create a `TableDataRowBackgroundProvider` like this one:
```
    private static class AlternatingTableDataRowColorProvider implements TableDataRowBackgroundProvider<Object> {

        @Override
        public Drawable getRowBackground(final int rowIndex, final YourData rowData) {
            if (rowData.hasCertainProperty()) {
                return new ColorDrawable(highlight color);
            }
            return new ColorDrawable(normalColor);
        }
    }
```

**Comment by aryst** [comment]
`    private static class AlternatingTableDataRowColorProvider implements TableDataRowBackgroundProvider<Data> {

        @Override
        public Drawable getRowBackground(int rowIndex, Data rowData) {
            if(rowData.getStatus().equals("")){
                return new ColorDrawable(Color.parseColor("#F69E9E"));
            }
            return new ColorDrawable(Color.parseColor("#FFFFFF"));
        }
    }
`

i have create this and when i call ### tb.setDataRowBackgroundProvider(new AlternatingTableDataRowColorProvider()); it said error " setDataRowBackgroundProvider (de.codecrafters.tableview.providers.TableDataRowBackgroundProvider<? super java.lang.String[]>) in TableView cannot be applied to (AlternatingTableDataRowColorProvider)"

**Comment by ISchwarz23** [comment]
Yes, the issue is that your table is of type String[] but your TableDataRowBackgroundProvidee is of type Object. So you need to give the generic like that:
```
AlternatingTableDataRowColorProvider implements TableDataRowBackgroundProvider<String[]> {

    @Override
    public Drawable getRowBackground(int rowIndex, String[] rowData) {
        if(rowData[].equals("")){
            return new ColorDrawable(Color.parseColor("#F69E9E"));
        }
        return new ColorDrawable(Color.parseColor("#FFFFFF"));
    }
}`
```
Of cause you have to change the index of the array access to the one where your status is stored.

**Comment by aryst** [comment]
okay thanks a lot i get it

**Comment by aryst** [comment]
i still got one problem. how to compare with value that is not show in the table

**Comment by ISchwarz23** [comment]
In this case you should not use a TableView of type String[] but of a POJO that represents your data.

But this would mean, that you have to write your custom TabeDataAdapter. This will create some work for you, but you are much more flexible in the future and have more possibilities in regards of rendering.

**Comment by aryst** [comment]
i do it in this way it work but when i scroll the color change

`    private class AlternatingTableDataRowColorProvider implements TableDataRowBackgroundProvider<String[]> {
        DatabaseHelper db = new DatabaseHelper(getApplicationContext());
        Cursor res = db.getStudentData(course_ID,section_ID,date,start_Time);

        @Override
        public Drawable getRowBackground(int rowIndex, String[] rowData) {
            int rowColor = Color.parseColor("#F69E9E");
            while (res.moveToNext()) {
                Log.d("test: ", "this" + res.getString(3));
                if (res.getString(3)!= null) {
                    rowColor = Color.parseColor("#FFFFFF");
                }
            }
            return new ColorDrawable(rowColor);

        }
    }
`

**Comment by aryst** [comment]
ok thanks i got it
