### ISSUE TITLE
Data Row Text Color

### ISSUE THREAD

**Issue by aryst** [ISchwarz23/SortableTableView#139]
hye is there anyway to set multiple color text color for data in table view?

**Comment by ISchwarz23** [comment]
Hi @aryst,

yes, there is a possibility. You could implementation a custom `TableDataAdapter`. This allows you to create a view for each table cell. In you case all of them would be `TextView`s, but you can set the colors for each of them.

Best regards,
Ingo

**Comment by aryst** [comment]
hi i got it. thanks.

One more problem. how to make sure the table refresh if the data is inserted to the table without scroll back to the top?
