### ISSUE TITLE
Table row height

### ISSUE THREAD

**Issue by aryst** [ISchwarz23/SortableTableView#141]
hye, is there a way to increase the table row height?

**Comment by ISchwarz23** [comment]
Hi @aryst,

which `TableDataAdapter` are you using?

Best regards,
Ingo

**Comment by aryst** [comment]
SimpleTableDataAdapter

**Comment by ISchwarz23** [comment]
Use `SimpleTableDataAdapter#setPaddingTop(int)` and `SimpleTableDataAdapter#setPaddingBottom(int)`.

The default value for too and bottom is 15.

**Comment by aryst** [comment]
i got it thank you
