### ISSUE TITLE
table view layout height

### ISSUE THREAD

**Issue by aryst** [ISchwarz23/SortableTableView#142]
hye,
i use dialog alert theme with table view. is there a way to dynamically expand the table view height based on data stored?

**Comment by ISchwarz23** [comment]
Hi @aryst,

so you talk about the height of a data row or the full table?

Best regards,
Ingo

**Comment by aryst** [comment]
Hye, 
I mean the full height of the table

**Comment by ISchwarz23** [comment]
No, this is not possible as the table behaves like a ListView.
But you can achieve this by setting the height of the table explicitly depending on the number of rows that are inside the table.

**Comment by aryst** [comment]
Okay I got it thanks

**Comment by hetsgandhi** [comment]
@ISchwarz23 Can you please share the code snippet for reference?
