### ISSUE TITLE
SimpleDataAdapter

### ISSUE THREAD

**Issue by aryst** [ISchwarz23/SortableTableView#145]
hye, 
for simpledataadapter, is there a way to make sure the long word will fully display in the tableview?

**Comment by ISchwarz23** [comment]
Hi @aryst,

no, the SimpleTableDataAdapter will create a TextView with a single line. If texts that are longer than the View it will be ellipsized at the end. If you want to have a different behavior you need to implement your own TableDataAdapter.

Best regards,
Ingo
