### ISSUE TITLE
color in some items 

### ISSUE THREAD

**Issue by azisoli** [ISchwarz23/SortableTableView#146]
hi 
in your demo picture you have some amount in price column with green and red color ?
how did you do that ? i couldn't find the code for that .
thanks

**Comment by ISchwarz23** [comment]
Hi @azisoli,

Check the [CarTableDataAdapter](https://github.com/ISchwarz23/SortableTableView/blob/master/app/src/main/java/de/codecrafters/tableviewexample/CarTableDataAdapter.java). More explicit have a look at the renderPrice() method.

Best regards,
Ingo
