### ISSUE TITLE
How to add Firebase or Firestore data to the table 

### ISSUE THREAD

**Issue by sleepymonq** [ISchwarz23/SortableTableView#148]
I have been trying for hours to fetch data stored in firestore/firebase to the ListView with the provided classes. Please provide an insight on how this is done in  your documentation.

**Comment by ISchwarz23** [comment]
Hi @sleepymonq,

thanks for using my library :)
For the table, there is no difference where your data is from. If it is inside memory, fetched from a Rest API or queried from a database. The table will only care for rendering your data that is present in a List as a table to the user.
So to see an example on how to fetch the data as a list from a Firebase check this [example](https://www.captechconsulting.com/blogs/firebase-realtime-database-android-tutorial).
Just implement a custom `TableDataAdapter` and use its `getData()` method to add, update and delete items (when receiving updates from the Firebase) and call the `notifyDataSetChanged()` to trigger a rendering of the new data.

Best regards,
Ingo
