### ISSUE TITLE
typo issue in your readme.md

### ISSUE THREAD

**Issue by mohammadrafigh** [ISchwarz23/SortableTableView#15]
hi again and sorry for making another issue :D,

in your readme.md in Colorizer part you mentioned this code:
`tableView.setDataRowColoriser(TableDataRowColorisers.alternatingRows(colorEvenRows, colorOddRows));`

but it should be actually TableDataRowColori"z"ers.

**Comment by ISchwarz23** [comment]
you don't have to excuse yourself for helping improving this library ;)
