### ISSUE TITLE
Table not working on tabbed activity pages

### ISSUE THREAD

**Issue by iampapagray** [ISchwarz23/SortableTableView#151]
Good work done.

when  i use this library on for instance an empty activty, it works fine. But when using it in a tabbed activity only the tableHeader background color is shown without the actual headers or the data.

Pls help

**Comment by ISchwarz23** [comment]
Hi @iampapagray,

unfortunately I can't help you with this amount of information. Please tell me which version on the TableView you are using. It would also be interesting to see your code and layouts.

Best regards,
Ingo

**Comment by iampapagray** [comment]
hi @ISchwarz23 ,
i have been able to fix it . thanks
