### ISSUE TITLE
horizontal scroll

### ISSUE THREAD

**Issue by elnazem** [ISchwarz23/SortableTableView#156]
how to make SortableTableView, horizontally scroll?

**Comment by elnazem** [comment]
https://github.com/ISchwarz23/SortableTableView/issues/14

**Comment by heybetzadec** [comment]
<HorizontalScrollView
                android:scrollIndicators="none"
                android:scrollbars="none"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content">

                <de.codecrafters.tableview.TableView
                    xmlns:table="http://schemas.android.com/apk/res-auto"
                    android:id="@+id/tableview"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    table:tableView_columnCount="5" />

            </HorizontalScrollView>
