### ISSUE TITLE
How to count values of the whole table when I have edit text like price ?

### ISSUE THREAD

**Issue by khouloudyaakoubi** [ISchwarz23/SortableTableView#158]
I have two problemes the first one is how to count the values of the whole table for example (price) and the second issue is how to paste data values from the first table to onother second table .
thanks .

**Comment by ISchwarz23** [comment]
Hi @khouloudyaakoubi,

wehn thinking about separation of data and view this is not a job that should be processed inside the view (TableView). Instead you can get the data from the view, calculate whatever you need and display it at the location you want.
If you need help regarding this approach I need information about Our DataAdapter.

Best regards,
Ingo

**Comment by khouloudyaakoubi** [comment]
Hi @ISchwarz23
thank you for your response . I need your help.
can you give me your email i will send you my issue.also my dataAdapter.
Thank you

**Comment by khouloudyaakoubi** [comment]
public class ModelTableDataAdapter extends LongPressAwareTableDataAdapter<Modele> {
    private static final int TEXT_SIZE = 17;
     private static int s =0;
    private static final NumberFormat NBASC = NumberFormat.getNumberInstance();
    public ModelTableDataAdapter(final Context context, final List<Modele> data, final TableView<Modele> tableView) {
        super(context, data, tableView);
    }


    @Override
    public View getDefaultCellView(int rowIndex, int columnIndex, ViewGroup parentView) {
        final Modele pro = getRowData(rowIndex);
        View renderedView = null;
    switch (columnIndex) {
            case 0:
                renderedView = renderModeleProjet(pro);
                break;
            case 1:
                renderedView = renderCatName(pro);
                break;

        }

        return renderedView;
    }

    @Override
    public View getLongPressCellView(int rowIndex, int columnIndex, ViewGroup parentView) {
        final Modele pro = getRowData(rowIndex);
        View renderedView = null;

        switch (columnIndex) {
            case 1:
                 renderedView = renderCaracteristiqueProjet(pro,parentView);

                break;
            default:
                renderedView = getDefaultCellView(rowIndex, columnIndex, parentView);
        }

        return renderedView;
    }
    //render Modele value
    private View renderModeleProjet(final Modele pro) {
        final TextView textView = new TextView(getContext());
        textView.setText(pro.getmodele());
        textView.setPadding(20, 10, 20, 10);
        textView.setTextSize(TEXT_SIZE);
        textView.setTextColor(getResources().getColor(R.color.navigationBarColor));
        textView.setTypeface(Typeface.DEFAULT_BOLD);
        return textView;
    }
    //post ASC value
    public View renderCaracteristiqueProjet(final Modele pro, final ViewGroup parentView) {
        final EditText editText = new EditText(getContext());
        editText.setText(pro.getNB_asc());
        editText.setPadding(20, 10, 20, 10);
        editText.setTextSize(TEXT_SIZE);
        editText.setSingleLine();
        editText.setTextColor(getResources().getColor(R.color.navigationBarColor));
        editText.setTypeface(Typeface.DEFAULT_BOLD);
        editText.setInputType(InputType.TYPE_CLASS_NUMBER);
        editText.setHint("entrer le nombre d'ascenseur");
        editText.addTextChangedListener(new CarNameUpdater(pro));
        editText.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                final Tooltip tooltip = new Tooltip.Builder(editText)
                        .setText("le nombre d'ascenseur doit être supérieur ou égal à 1")
                        .setBackgroundColor(getResources().getColor(R.color.grey4))
                        .setTextColor(getResources().getColor(R.color.colorPrimary))
                        .setGravity(Gravity.END)
                        .build();
                tooltip.show();
                Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    public void run() {
                        tooltip.dismiss();
                    }
                }, 5000);
                return false;
            }

        });

        return editText;
    }
    private View renderCatName(final Modele car)
    {
        return renderString(car.getNB_asc());


    }



    private View renderString(final String value) {
        final TextView textView = new TextView(getContext());
        textView.setText(value);
        textView.setPadding(20, 10, 20, 10);
        textView.setTextSize(TEXT_SIZE);

        return textView;
    }

    private static class CarNameUpdater implements TextWatcher {

        private Modele carToUpdate;

        public CarNameUpdater(Modele carToUpdate) {
            this.carToUpdate = carToUpdate;
        }

        @Override
        public void beforeTextChanged(CharSequence s, int start, int count, int after) {
            // no used
        }

        @Override
        public void onTextChanged(CharSequence s, int start, int before, int count) {
            // not used
        }

        @Override
        public void afterTextChanged(Editable s) {

            carToUpdate.SetNBASC(s.toString());
        }

    }
}
==> this is my adapter i want to calculate the whole values after entered by user and save the new value.

**Comment by ISchwarz23** [comment]
So, the values entered by the user are already passed to the data as NBASC. Unfortunately the NBASC are Strings, so I don't know how you want to sum then up.

As improvement I would store the NBASC as number. Then as soon as all values are entered (don't know if this is user triggered or shall be automatically) iterate over your list of Modele and calculate the sum of NBASCs.

**Comment by khouloudyaakoubi** [comment]
yes NBASC are strings i parse it  to integer then i calculate the sum but no result :'( also i can't save all values entered by the user i mean when i pass from other activity then then back to the first one the values entered disapears.

**Comment by khouloudyaakoubi** [comment]
public class Modele
{
    private String modele;
    private String nb_ASC;
    private String somme;


    public Modele( String modele, String nb_ASC)
    {  // this.carProducer=carProducer;
        this.modele = modele;
        this.nb_ASC = nb_ASC;
    }
    public String getmodele() {
        return modele;
    }
    public String getNB_asc() {
        return nb_ASC;
    }
    public String getSommeASC(){return somme;}
    public void SetNBASC(String nb_ASC)
    {this.nb_ASC=nb_ASC;}
    public Modele() {

    }
}
==> this is my modele
and this is how i fill data 
public class DataModele
{ //create a table of nb model asc :
    public static List<Modele> createModeleList(Context context)
    {
        int s=0;
        SharedPreferences sharedpref14=context.getSharedPreferences("MyPREFERENCES", Context.MODE_PRIVATE);
        String numModele=sharedpref14.getString("nbmodele","");
        int nbM=Integer.parseInt(numModele);
        Modele m = new Modele();
        List<Modele> projets = new ArrayList<>();
        for (int i=1;i<=nbM;i++)
        {   StringBuilder sb = new StringBuilder();
            sb.append("");
            sb.append(i);
            String strI = sb.toString();
            projets.add(new Modele(strI," "));

        }
        return projets;

}

}

**Comment by khouloudyaakoubi** [comment]
![tableau asc](https://user-images.githubusercontent.com/40357056/41594368-1a824384-73bb-11e8-9e2e-d761e6c6f36e.PNG)

**Comment by khouloudyaakoubi** [comment]
![tableau pro](https://user-images.githubusercontent.com/40357056/41594422-465d4d00-73bb-11e8-8ce6-86ec70b1f8bf.PNG)
==> I want to pass nb asc from the first table to the second table (two activities) also calculate the sum of NBASC.

**Comment by ISchwarz23** [comment]
As you have identified yourself the issue has nothing to do with the table itself. It is about passing the modified data back to the first activity.

There are multiple ways to solve this issue, e.g.
- Call the second activity for result (https://developer.android.com/training/basics/intents/result)
- Store the modified data from the second activity to your shared preferences and load it in first activity onResume()
- ...

As this issue is not related to this library I am going to close it.

**Comment by khouloudyaakoubi** [comment]
thank you
