### ISSUE TITLE
Is it possible to give word wrap to table contents?

### ISSUE THREAD

**Issue by yigitserin** [ISchwarz23/SortableTableView#16]
Hi there,

In my table, I need to display rather long values but it does not fit. Can I word wrap the texts?

Thanks!

**Comment by ISchwarz23** [comment]
Hi again ;)

do you only display strings in your table? And do you want to wrap the text for all strings or just in certain columns?

Best regards,
Ingo

**Comment by yigitserin** [comment]
Hello,
Yeah only strings are viewed and for all columns if possible.

**Comment by ISchwarz23** [comment]
So, always if you want to change the representation of your data inside a cell you need to touch the `TableDataAdapter`. Therefor you can create a custom `TableDataAdapter` which extends the `SimpleTableDataAdapter` and sets the wrapping for the `TextView` created by the `SimpleTableDataAdapter`.

```
public class WrapTextTableAdapter extends SimpleTableDataAdapter {

   @Override
    public View getCellView(final int rowIndex, final int columnIndex, final ViewGroup parentView) {
        TextView textView = (TextView) super.getCellView(rowIndex, columnIndex, parentView);
        textView.setSingleLine(false);
        textView.setEllipsize(0);
        ...
        return textView;
    }

}
```

**Comment by yigitserin** [comment]
Thanks! It works perfectly now!
