### ISSUE TITLE
sort table except last row

### ISSUE THREAD

**Issue by DanVilGui** [ISchwarz23/SortableTableView#161]
hi, I want to sort rows by a column except last row , how can i do this ? 

thanks in advance

**Comment by ISchwarz23** [comment]
Hi @DanVilGui,

What type of data do you have in your table? String arrays or custom objects?

Best regards,
Ingo

**Comment by DanVilGui** [comment]
Custom objects

**Comment by ISchwarz23** [comment]
Can you distinguish the last object from the other objects? (Except of it's index)

**Comment by ISchwarz23** [comment]
So write your own comparator like this:

```java
public class TotalAwareComparator implements Comparator<YourObject> {

    private final SortableTableView tableView;

    public TotalAwareComparator(SortableTableView tableView) {
        this.tableView = tableView;
    }

    public int compare(YourObject obj1, YourObject obj2) {
        if(obj1.isTotal()) {
            return tableView.getSortState().getSortedOrder() == SortingOrder.ASCENDING ? 1 : -1;
        } else if(obj2.isTotal()) {
            return tableView.getSortState().getSortedOrder() == SortingOrder.ASCENDING ? -1 : 1;
        } else {
            // do normal sorting
        }
    }

}
```

I wrote this code on my mobile so there may are some errors. Also I may swapped the return values for the "total objects".

**Comment by DanVilGui** [comment]
thank you so much

**Comment by c0dehunter** [comment]
> I wrote this code on my mobile.

You, sir, deserve a medal.

**Comment by c0dehunter** [comment]
> So write your own comparator like this:
> 
> ```java
> public class TotalAwareComparator implements Comparator<YourObject> {
> 
>     private final SortableTableView tableView;
> 
>     public TotalAwareComparator(SortableTableView tableView) {
>         this.tableView = tableView;
>     }
> 
>     public int compare(YourObject obj1, YourObject obj2) {
>         if(obj1.isTotal()) {
>             return tableView.getSortState().getSortedOrder() == SortingOrder.ASCENDING ? 1 : -1;
>         } else if(obj2.isTotal()) {
>             return tableView.getSortState().getSortedOrder() == SortingOrder.ASCENDING ? -1 : 1;
>         } else {
>             // do normal sorting
>         }
>     }
> 
> }
> ```
> 
> I wrote this code on my mobile so there may are some errors. Also I may swapped the return values for the "total objects".

**Comment by rajam1215** [comment]
@DanVilGui can you solve my issue regarding total like you,
