### ISSUE TITLE
Change the text size in header and rows

### ISSUE THREAD

**Issue by kk99999** [ISchwarz23/SortableTableView#163]
How can i specify the size of text for the header as well as for the rows.

**Comment by ISchwarz23** [comment]
Hi @kk99999,

If you are using the `SimpleTableDataAdapter` and `SimpleTableHeaderAdapter` you should use the `setTextSize( int )` method.

Regards,
Ingo

**Comment by kk99999** [comment]
Hi Ingo, Thank you.
