### ISSUE TITLE
is there a possibility to set one of the header as a image?

### ISSUE THREAD

**Issue by ArunPandiyan** [ISchwarz23/SortableTableView#17]
is there a possibility to set one of the header as a image?

**Comment by ISchwarz23** [comment]
Hi ArunPandiyan,

yes of cause this is possible ;) You can do so by writing your own `TableHeaderAdapter`. Here is an example for a CustomTableHeaderAdapter that shows an `ImageView` in the first column, a CustomView in the second column and a `TextView` in all other columns.

```
public final class SimpleTableHeaderAdapter extends TableHeaderAdapter {

    @Override
    public View getHeaderView(final int columnIndex, final ViewGroup parentView) {
        switch( columnIndex ) {
            case 0: return new ImageView(getContext());
            case 1: return new MyFancyView(getContext());
            default: return new TextView(getContext());
        }
    }

}
```
As you see you can use the `getContext()` method of the `TableHeaderAdapter` to initiate new `View`s. (In this example all views are empty, but you can fill them like you need it.)   
When you have created your custom `TableHeaderAdapter` you can set this to your `TableView` (or `SortableTableView`).
```
    tableView.setHeaderAdapter( new CustomTableHeaderAdapter( context ) );
```

**Comment by arunsq** [comment]
Thanks ISchwarz23, for a quick response. I was implementing custom tableheader as you did in the example, but 

> tableView.setHeaderAdapter( new CustomTableHeaderAdapter( context ) );

i missed to add the above line to the tableview.
