### ISSUE TITLE
Search specific item?

### ISSUE THREAD

**Issue by nicemak** [ISchwarz23/SortableTableView#171]
Hi,
Is there any way to search in tableview for specific item?
Like i have hundreds of items and i want to search for an item and scroll list to that item.
please tell me if there is way. Thanks

**Comment by ISchwarz23** [comment]
Hi @nicemak,

unfortunatelly this is not supported out of the box.
The pro version supports filtering. You can test the feature in the [Example App](https://play.google.com/store/apps/details?id=com.sortabletableview.recyclerview.exampleapp). More information about the pro version can be found here: www.sortabletableview.com

Regards,
Ingo
