### ISSUE TITLE
Remove divider

### ISSUE THREAD

**Issue by javmorales** [ISchwarz23/SortableTableView#176]
problem is resolved

**Comment by ISchwarz23** [comment]
You can set the devider color to transparent and/or the devider height to 0dp. Here is an example how to set the mentioned attributes:
```xml
<de.codecrafters.tableview.TableView
    android:id="@+id/tableView"
    ...
    android:divider="@color/black"
    android:dividerHeight="1dp"
    ...  /> 
```

**Comment by javmorales** [comment]
> You can set the devider color to transparent and/or the devider height to 0dp. Here is an example how to set the mentioned attributes:
> 
> ```
> <de.codecrafters.tableview.TableView
>     android:id="@+id/tableView"
>     ...
>     android:divider="@color/black"
>     android:dividerHeight="1dp"
>     ... > 
> ```

**Comment by javmorales** [comment]
and other question, if i not using object only SimpleTableDataAdapter how i can addClickListener? thanks for all. Sorry for my bad english
