### ISSUE TITLE
changing text size

### ISSUE THREAD

**Issue by kimsungbo** [ISchwarz23/SortableTableView#188]
is there any way for me to change the font size of the table contents?

**Comment by ISchwarz23** [comment]
Hi @kimsungbo,
when you are using the `SimpleTableDataAdapter` you can call the Methode `setTextSize()`.

**Comment by asiamatrix** [comment]
Hi @ISchwarz23 
I used SortableTableView. How can I change text size and alignment?
Thank You.

**Comment by ISchwarz23** [comment]
Hi @asiamatrix,

when using the `SimpleTableDataAdapter` you can set the text size using `SimpleTableDataAdapter#setTextSize( int )` and set the alignment using `SimpleTableDataAdapter#setGravity( int )`.
An example gravity would be `Gravity.END`.
