### ISSUE TITLE
Apply sorting on date column:

### ISSUE THREAD

**Issue by sanakalam** [ISchwarz23/SortableTableView#189]
I want to apply sorting on date column but there is an issue date is also considered as a string and 1st date of all months shown then 2nd date of all month showing.
How can we manage sorting for date column
![image](https://user-images.githubusercontent.com/54615542/77147055-41dbd080-6aae-11ea-89be-a106a8db6260.png)

**Comment by ISchwarz23** [comment]
Hi @sanakalam,

can you pleas show your comparator for the date column?

Best regards,
Ingo

**Comment by sanakalam** [comment]
tableView.**setColumnComparator**(6, new Comparator<RequestInquiryModel>() {
                @Override
                public int compare(RequestInquiryModel o1, RequestInquiryModel o2) {
                    return o1.getCreatedOn().compareTo(o2.getCreatedOn());
                }
            });

**Comment by ISchwarz23** [comment]
What data type does `getCreatedOn()` return? String?

**Comment by sanakalam** [comment]
yeah String. I am fetching data from API and date return as a String

**Comment by ISchwarz23** [comment]
I would suggest to transform the string to date using `SimpleDateFormat`.

**Comment by sanakalam** [comment]
SimpleTableDataColumnAdapter c7 = new SimpleTableDataColumnAdapter<>((SimpleTableDataColumnAdapter.**StringValueExtractor**<RequestInquiryModel>) data -> data.getCreatedOn().toString());

For Date which method we have to use instead of **StringValueExtractor**  because it only accepts String value.

**Comment by ISchwarz23** [comment]
Hi you can use `SimpleDateFormat` to turn you `Date` into a `String`.

```java
SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd"); // TODO: adapt pattern

SimpleTableDataColumnAdapter c7 = new SimpleTableDataColumnAdapter<>(
    (SimpleTableDataColumnAdapter.StringValueExtractor) data -> dateFormatter.format(data.getCreatedOn()));
```

**Comment by sanakalam** [comment]
@ISchwarz23  Thanks For your Support.
I use below code it works:
 SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
            tableView.setColumnComparator(6, new Comparator<RequestInquiryModel>() {
                @Override
                public int compare(RequestInquiryModel o1, RequestInquiryModel o2) {
                    Date d1=null;
                    Date d2=null;
                    try {
                        d1=format.parse(o1.getCreatedOn());
                        d2=format.parse(o2.getCreatedOn());
                    } catch (ParseException e) {
                        e.printStackTrace();
                    }
                    return d1.compareTo(d2);
                }
