### ISSUE TITLE
How do I get the cell content?

### ISSUE THREAD

**Issue by Fdde11** [ISchwarz23/SortableTableView#191]
Hi! I have a sorting table and when I sort my data I lose track of my IDs in another array, therefore, I want to extract the data directly from any cell but I can't find a way to do it. 
I already have a  DataClickListener but since I'm sorting the data the rowIndex doesn't help.

**Comment by ISchwarz23** [comment]
Hi @Fdde11,
you can use a custom TableDataAdapter. In this case the complete object (with I'd) is passed to the on click callback method.
