### ISSUE TITLE
"Mark" selected row without using a custom TableView Adapter?

### ISSUE THREAD

**Issue by Fdde11** [ISchwarz23/SortableTableView#192]
Is it possible to "mark" the row the user selected (DataClickListener)? be it changing the row background color or text color or anything that indicates the user which row was selected.

**Comment by ISchwarz23** [comment]
Hi @Fdde11,

in the free version there is nothing available out of the box. But you can have it in the pro version. If you are interested have a look at www.sortabletableview.com.

Nevertheless you can implement it on your own, by adding a flag to.your data (e.g. "selected"). This flag shall be set by the on click listener. Then all you need to do is implement a custom  `TableDataRowBackgroundProvider` that will return a different background for rows where the "selected" flag is true.

Kind regards,
  Ingo

**Comment by Fdde11** [comment]
Understood, many thanks :)
