### ISSUE TITLE
Implement custom TableDataRowBackgroundProvider without re-populate table

### ISSUE THREAD

**Issue by Fdde11** [ISchwarz23/SortableTableView#197]
Hi, in order to set a selected row I created a custom TableDataRowBackgroundProvider the problem I'm having is that in order for the selected row background to show I have re-populate my table which causes the table to scroll back to the top.

is there a way to implement my custom TableDataRowBackgroundProvider without having to reload my table? 
right now I'm doing this
```Java
SelectedRowColorProvider selrow= new SelectedRowColorProvider();
tableObras.setDataRowBackgroundProvider(selrow);
```

inside an addDataClickListener

or 

if I have to reload my table how can I scroll back to my selected index?

**Comment by ISchwarz23** [comment]
You can set the SelectedRowColorProvider once to you table (not on click). And on click you set the item.selected and call the `TableDataAdapter#notifyDataSetChanged()` method.

**Comment by Fdde11** [comment]
> You can set the SelectedRowColorProvider once to you table (not on click). And on click you set the item.selected and call the `TableDataAdapter#notifyDataSetChanged()` method.

That worked! many thanks
