### ISSUE TITLE
Add footer view

### ISSUE THREAD

**Issue by c0dehunter** [ISchwarz23/SortableTableView#199]
How could I add a footer view, stretching the whole width? Adding it in getCellView() is not OK, because I have 4 cells. The footer view would be a simple button to add more data.

**Comment by ISchwarz23** [comment]
Hi @c0dehunter,

there is no way to achieve this inside the table. The only thing you can do is to add the button below the table.

Best regards,
Ingo

**Comment by c0dehunter** [comment]
Thank you for the input. How could I achieve to place the button **below** the table in my case? I can put it under table so it always shows, but I want the user to see it only after it scrolled to bottom of table. I experimented with nesting the _SortableTableView_ inside a _ScrollLayout_ and then adding a button on bottom, but it doesn't work (I don't see the table). 

![image](https://user-images.githubusercontent.com/1484658/88619124-591a7280-d0cd-11ea-86fb-77f526c0a9be.png)

I understand this is not an issue of SortableTableView, but I would appreciate the input, if you have any idea.

**Comment by ISchwarz23** [comment]
Hi @c0dehunter,

how about adding the button always visible to the bottom of the table (as you already did) and then add a ScrollListener to the table which will make the button visible when the user scrolled to the bottom and makes it gone when the user scrolls up again. This would look better when you apply animations to the button.

Best regards,
Ingo

PS: I like you UI but the table doesn't fit the style of the application. You can colorize the header and the rows to match the chart above.

**Comment by c0dehunter** [comment]
Hi, 

that's a good idea, thanks! Will try with ScrollListener.

Regarding the UI - yes, I really need to make a UI clean-up for the whole app. It's planned soon :) 

Thank you for your library.
