### ISSUE TITLE
Header doesn't appear

### ISSUE THREAD

**Issue by JulienDev** [ISchwarz23/SortableTableView#2]
Hi,

There is an issue with the library when I want to use header. If I don't put any view above the SortableTableView, the header never appears. Some examples with your sample : 
- Remove the toolbar in activity_main.xml
- Replace RelativeLayout by a LinearLayout

I think it's an issue because we don't need RelativeLayout everytime. The only workaround I found is using a fakeView above the TableView:

```
<View
    android:id="@+id/fakeView"
    android:layout_width="match_parent"
    android:layout_height="1dp"
    android:background="?attr/colorPrimary"/>

<fr.fnac.connect.ui.component.SortableProductTableView
    android:id="@+id/comparison_table"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_below="@id/fakeView"
    app:columnCount="4"
    app:headerColor="?attr/colorPrimary"
    app:headerElevation="10"/>
```

Julien

**Comment by ISchwarz23** [comment]
I just tested your scenario and it worked for me. I was using this layout file (modification of the activity-main.xml following your description):
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                xmlns:custom="http://schemas.android.com/apk/res-auto"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                tools:context="de.codecrafters.tableviewexample.MainActivity">

    <de.codecrafters.tableviewexample.SortableCarTableView
        android:id="@+id/tableView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        custom:columnCount="4"
        custom:headerElevation="10"
        custom:headerColor="?attr/colorPrimary" />

</LinearLayout>
```

Can you ensure that the issue is caused by the layout the TableView is in? Or maybe the error is in a different place? Please tell me if you have some new knowledge. I will also do some investigations.

**Comment by JulienDev** [comment]
Hi, I was able to reproduce the issue by creating 1 activity : HomeActivity & 2 fragments : HomeFragment & TableFragment

HomeActivity has a FrameLayout container R.id.container

I have 2 scenarios : 
- Inside onCreate I add the HomeFragment then when I select the entry menu in my drawerlayout I replace the fragment by TableFragment : Header does **not** appear. The only way workaround I found is adding the fakeView as explained yesterday.
- Inside onCreate I add the TableFragment : Header does appear

I really don't understand why the issue happens. Some informations about my project:
compileSdkVersion 22
buildToolsVersion "22.0.1"
minSdkVersion 21
targetSdkVersion 22
I use https://github.com/mikepenz/MaterialDrawer

**Comment by ISchwarz23** [comment]
I think that I fixed the issue. 
Please try the **version 0.9.4** and give some feedback if the issue is really fixed.

**Comment by JulienDev** [comment]
Sorry for the delay, it works fine :)
Thanks !

**Comment by CoolCommando** [comment]
Hi, I have the same/similar problem with the latest version(2.4.1)- Header text does not appear when the SortableTableView is used in a fragment. The header is just a blank space. I can set the Header background color using the sortableTableView.setHeaderBackgroundColor(). No methods in the SimpleTableHeaderAdapter class seem to be working. 
 Note that if I use the older version- 0.9.4 the the header text does appear.

My code inside the onCreateView of the Fragment:

 SimpleTableHeaderAdapter headerAdapter = new SimpleTableHeaderAdapter(mContext, "A", "B", "C", "D");
        headerAdapter.setTextColor(Color.parseColor("#000000"));

        TableView<String[]> sortableTableView = (TableView<String[]>)        rootView.findViewById(R.id.tableView);
        sortableTableView.setDataAdapter(new SimpleTableDataAdapter(mContext, DATA_TO_SHOW));
        sortableTableView.setColumnCount(4);
        sortableTableView.setHeaderBackgroundColor(Color.parseColor("#FFFFFF"));
        sortableTableView.setHeaderElevation(10);
        sortableTableView.setHeaderAdapter(headerAdapter);

Layout:

 <de.codecrafters.tableview.SortableTableView
        android:id="@+id/tableView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_margin="5dp"
        android:background="#dafdea"
        />

Please let me know if I'm doing anything incorrectly.

Thanks,
Sujith

**Comment by Sineth-N** [comment]
I'm afraid that I too see the exact same issue as well.
I did what is explained by  @CoolCommando . Check the screenshot please

![device-2017-01-28-131223](https://cloud.githubusercontent.com/assets/9636665/22396382/6fa21bfe-e57e-11e6-83d2-9fce60e84886.png)

**Comment by ISchwarz23** [comment]
Hi @Sineth-N,

could you please try your code with the new TableView version 2.4.3 and report if this issue is fixed?

Best regards,
Ingo

**Comment by Sineth-N** [comment]
Hi @ISchwarz23 ,
It works now YAY!!!.. Awesome work done by you here, keep up the good work mate.... Cheers!!!

**Comment by softwaresunleashed** [comment]
For me , getView() is not being hit....I have put breakpoints and they are not being hit.
Is this a known issue?
