### ISSUE TITLE
Header shriking while creating several columns

### ISSUE THREAD

**Issue by gabrieltm** [ISchwarz23/SortableTableView#20]
First, i want to thank you for this amazing lib.

I have a problem while creating several columns, they are shrinking in size and the columns names stay like ("header here..."), i have tried to increase the setColumnWeight but with no success, i already added the horizontal scroll view like the other issues presented. Is there any way to increase the width of the columns ?

**Comment by ISchwarz23** [comment]
Hi gabrieltm,
I think you are using the TableView using the size attributes `match_parent`. As you have the TableView inside a HorizontalScollView so you can simplify set a fixed width to the TableView and then adjust the column widths by giving specific weights.   
Is this What you are trying to achive?

**Comment by gabrieltm** [comment]
Actually, when i try to set specific weights on my SortableTableView, some of the other columns shrink in size, also some data in the rows also automatically wrap their texts.

Is there a way to make all texts of the rows in a single line only and make them adjust their column width by their size ? I want this for the Headers also if the row data text size is smaller than the headers text size.

**Comment by ISchwarz23** [comment]
Yes, you can prevent the table data to be wrapped by writing your custom `TableDataAdapter`.
```java
public class SingleLineTableDataAdapter extends SimpleTableDataAdapter {

    public SimpleTableDataAdapter(final Context context, final String[][] data) {
        super(context, data);
    }

    public SimpleTableDataAdapter(final Context context, final List<String[]> data) {
        super(context, data);
    }

   @Override
    public View getCellView(final int rowIndex, final int columnIndex, final ViewGroup parentView) {
        TextView textView = (TextView) super.getCellView(rowIndex, columnIndex, parentView);
        textView.setSingleLine(true);
        textView.setLines(1);
        textView.setEllipsize(null);
        ...
        return textView;
    }

}
```

Unfortunately the `TableView` is not accepting `WRAP_CONTENT` as width parameter. So your text will be simply cut off. But at least with the next bug fix version you will be able to set an absolute width (e.g. `android:layout_width="900dp"`).

**Comment by gabrieltm** [comment]
Hello,

So it's not possible to prevent this bug of getting my text of the headers being cut off ?

**Comment by ISchwarz23** [comment]
The bug fix version will be finished this week. Then you are able to put the TableView inside a HorizontalScollView and set a fixes width.
Does this fulfill your needs?

**Comment by gabrieltm** [comment]
Sure does ! Thank you very much man

**Comment by ISchwarz23** [comment]
Have a try `de.codecrafters.tableview:tableview:1.1.1` ;)  
Please give me feedback if it is working correctly.

**Comment by gabrieltm** [comment]
I'm having a problem while trying to execute the project with the new 1.1.1 library.

>Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v7/appcompat/R$anim.class

Do you have any idea why is this happening ? By the way i upgraded my android studio to 2.0 and gradle build to 2.0

**Comment by ISchwarz23** [comment]
Hi @gabrieltm,  
can you please give feeback, if this error still occurs?  
Best regards,
Ingo
