### ISSUE TITLE
Sort

### ISSUE THREAD

**Issue by The28AWG** [ISchwarz23/SortableTableView#23]
Hello!
How to add many sort algorithm?
```java
    private static class MySortStateViewProvider implements SortStateViewProvider {

        private static final int NO_IMAGE_RES = -1;

        @Override
        public int getSortStateViewResource(SortState state) {
            switch (state) {
                case SORTABLE:
                    return R.mipmap.ic_sortable;
                case SORTED_ASC:
                    return R.mipmap.ic_sorted_asc;
                case SORTED_DESC:
                    return R.mipmap.ic_sorted_desc;
                default:
                    return NO_IMAGE_RES;
            }
        }
    }
```
Need more sorting algorithm.
Exapmle:
| header |
| new |
| pending |
| done |
| pending |
| pending |
| done |
How to sort "first new" or "first done"? Use Comparator? 
```java
sortableTableView.setColumnComparator(0, new CarProducerComparator());
```
No! Comparator sort "-1, 0, 1".
And need more sorting button, or popup menu.
Sorry my bad english. =(

**Comment by ISchwarz23** [comment]
Hi Ruslan,

I would like to start with an explanation about the concept how this library was intended to be used :)

1) the code you have posted is a `SortStateViewProvider` which is responsible of giving a "image" that shall be shown for a certain `SortState` in the column header e.g. an arrow up for `SortState.SORTED_ASC`.  
2) The algorithm that is used for sorting the items of the table is fixed and can not be changed. I used the sort algorithm of the java collection which is a stable sort algorithm that guarantees n log n complexity (MergeSort).  
3) The `Comparator<T>` is a simple entity, which defines the sorting order for a certain data type. I think this is exactly what you try to do. As the Comparator interface is part of standard java there is a lot of information and examples available in the web e.g. the [Java API Description](https://docs.oracle.com/javase/7/docs/api/java/util/Comparator.html).  

For your concrete example I would go for an `Enum` representing your (lets call it) `State`. This `State` holds the information about the sequence of the defined states (which one comes first, which second, which third).
```java
public enum State {

    NEW(1),
    PENDING(2),
    DONE(3);

    private int sequence;

    Status(int sequence) {
        this.sequence = sequence;
    }

    public int getSequence() {
        return sequence;
    }

}
```

Now you can create a `Comparator` which is able to transform the sequence information to the sort information (-1, 0, 1).
```java
public class StateComparator implements Comparator<State> {

    @Override
    public int compare(State firstState, State secondState) {
        return firstState.getSequence() - secondState.getSequence();
    }

}
```

This `Comparator` could now be set to a column in you `SortableTableView`. If you do not manage to transfer this example to your use case I offer to help you with this.

Best regards,
Ingo

**Comment by The28AWG** [comment]
Its, work! Thanks!
