### ISSUE TITLE
Scrollbar not present

### ISSUE THREAD

**Issue by ciskeboekelo** [ISchwarz23/SortableTableView#25]
Hi,

Thanks for this library!

On my Nexus 6 running Android 5.1.1 and my Nexus 7 (2103) running 6.01, I'm not seeing a scrollbar in my tableview. 

Do I need to do something different or is this a bug?

**Comment by ciskeboekelo** [comment]
Just checked the sample app on my Nexus 7: same thing.

**Comment by ISchwarz23** [comment]
Hi @ciskeboekelo,  
thanks for this hint. Fact is, that the TableView is currently not showing a scrollbar at all. But you are right, maybe it is helpfull to have such an indicator, especially in TableViews with a large data set. I think this will be an upcomming feature. :)  
Best regards,
Ingo

**Comment by ciskeboekelo** [comment]
Ok, so it's not me then :-)
But then how come there is a scroll bar in the animated GIF in the readme?

**Comment by ISchwarz23** [comment]
I have no idea. There has been no change corresponding to that. It's still a standard ListView. But nevertheless there should be some possibility for the TableView to adapt this.

**Comment by ciskeboekelo** [comment]
I found the cause of this issue and have created a PR with a fix. 
If you agree with the fix, could you merge it and release a new version? Thanks!

**Comment by ISchwarz23** [comment]
Thanks you very much for your effort. I will do exactly that ;)

**Comment by ISchwarz23** [comment]
Have fun with the new release `compile 'de.codecrafters.tableview:tableview:2.0.1'` and thank you!

**Comment by ciskeboekelo** [comment]
Works like a charm! Thanks for the quick update!
