### ISSUE TITLE
Cell click event in the table

### ISSUE THREAD

**Issue by vinykumar** [ISchwarz23/SortableTableView#29]
Hi,
      Thanks for the library. It's really helpful.

Can you please tell me how to write **click event on the each table cell to get the cell value**.

Thank You
-Vinay

**Comment by ISchwarz23** [comment]
Hi @vinykumar,

unfortunatelly it is currently only possible to listen for clicks on a certain row. This decision was done, as one row should represent one data item. So you can listen for clicks on rows (or data items) but not on a certain cell (or attribute of a data item).

Best regards,
Ingo

**Comment by captrespect** [comment]
If you want to do this, just add a custom view like in the example and add your own click listener.

**Comment by ISchwarz23** [comment]
Thanks @captrespect, this is a possible way to get the clicked column, row and item. By adding this click listener, it the TableDataClickListener is not informed anymore, as the custom view "consumes" this click.
