### ISSUE TITLE
 tableview folder . newbie

### ISSUE THREAD

**Issue by yassinejhon** [ISchwarz23/SortableTableView#33]
Hi im newbie 

It says

To use the this library in your project simply add the following dependency to your build.gradle file.

 dependencies {
        compile 'de.codecrafters.tableview:tableview:0.9.5'
    }
 
It's clear that I should copy the tableview folder and add the dependencies on build.gradle. Where should I copy the tableview folder to?

**Comment by ISchwarz23** [comment]
Hi @yassinejhon,  

first, I would like to recommend to usr the latest Version of the TableView which is currently Version 2.0.1.  
Second, you should get used to gradle. By defining the TableView artifact as compile dependency gradle will automatically searches for it on the defined artifact repository, downloads it and links it to your project. By default JCenter is defined as artifact repository for Android projects. As the TableView was uploaded to JCenter you can use the TableView by simple adding the dependency to your build.gradle without copying anything anywhere.  

Best regards,
Ingo

**Comment by yassinejhon** [comment]
thanks it works , i am used to eclipse i installed android studio just to use your library thanks
