### ISSUE TITLE
gravity header

### ISSUE THREAD

**Issue by dwinetralizme** [ISchwarz23/SortableTableView#34]
hi, can i set gravity header?
thanks

**Comment by ISchwarz23** [comment]
Hi @dwinetralizme,  

could you please explain in more details what your need is. Do you want to set the gravity to any view in a header cell, or do you need to set the gravity to a TextView in a header cell, or do you want to set the gravity to the sorting indicators, or something totally different?  

Best regards,
Ingo

**Comment by dwinetralizme** [comment]
mr @ISchwarz23 yes i need to set the gravity position centre and set position right to the sorting indicators. can you help me.

thx

**Comment by ISchwarz23** [comment]
The (Sortable)-TableView provides the native RTL support. So, if you have set the `android:supportRtl="true"` in your manifest file, the columns as well as the sorting indecators will be rtl or ltr corresponding to the locale/language. But unfortunatelly there is no way to define the position of the sorting indicators. In ltr they are on the left and in rtl they are on the right. There is no way on setting this programatically. The only thing you can adapt is the header cell for each column header. There you can do what ever you want by implementing an `TableHeaderAdapter`. You can also create your own `SortingStateViewProvider` which gives an DrawableResource that will be shown for a certain SortState, but the position of the provided image resource will be defined by the table.  

So the short answer to your question is: No, unfortunatelly it is not possible.
