### ISSUE TITLE
Remove the TableView's internal ScrollView

### ISSUE THREAD

**Issue by ahmadalibaloch** [ISchwarz23/SortableTableView#36]
This is not needed and can easily be implemented if needed. The problem due to this can be explained like this.

When I have tableView at the lower end of my LinearLayout layout (or any) where only 1 row can be visible. Then the tableView's internal scrollview starts scrolling that one row but I want to scroll all the screen up to see more than one rows. This is only possible when tableView expand itself beyond the screen in a parent scrollView which holds all the screen.

Here is my tableView layout in a LinearLayout with many siblings that are all in a ScrollView vertical.
`
            <com.dgheating.mobileapp.Data.SortableProductTable xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:table="http://schemas.android.com/apk/res-auto"
                android:id="@+id/tableViewProducts"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:divider="@color/dividerDarkGrey"
                android:dividerHeight="1dip"
                table:columnCount="5"
                table:headerColor="@color/colorPrimary" />`

![untitled](https://cloud.githubusercontent.com/assets/1916642/15804502/3d6533ac-2b24-11e6-992b-cadd8b1f5021.jpg)

See in the screen shot I can't scroll the screen up because tableView is not expanding based on its content.

**Comment by captrespect** [comment]
This would be tough because the internal view is a ListView.  I've been able to work around the issue by inflating all the rows, measuring the height and then setting the height on the ListView. 

See the setListViewHeightBasedOnChildren method here:http://stackoverflow.com/questions/18367522/android-list-view-inside-a-scroll-view

**Comment by ahmadalibaloch** [comment]
This solution is not working for TableView.

> See the setListViewHeightBasedOnChildren method here:http://stackoverflow.com/questions/18367522/android-list-view-inside-a-scroll-view
