### ISSUE TITLE
Getting error while adding the dependency

### ISSUE THREAD

**Issue by sdutta9** [ISchwarz23/SortableTableView#39]
Hi I am new to android. As you mentioned in your read me file. I added a dependency in build.gradle file. When I am trying to sync my gradle file I am getting the below error. 

"Error:(27, 13) Failed to resolve: de.codecrafters.tableview:tableview:2.1.0"

Can you please help me understand as to how I can add dependency in my application. Is there any other step that needs to be done apart from putting an entry in the gradle file?

**Comment by ISchwarz23** [comment]
Hi @sdutta9,

could you please post the content of your 'dependencies' section of your gradle file inside the "App" folder?

Best regards,
Ingo

**Comment by sdutta9** [comment]
Below is my complete build.gradle file:
-------------------------------------------------------------------------------------------------------------------
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "shouvik.dutta.serviceupdate"
        minSdkVersion 11
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
repositories {
    mavenCentral()
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'de.codecrafters.tableview:tableview:2.1.0'
}

**Comment by sdutta9** [comment]
Screenshot of the error:
---------------------------------------------------------------------------------------------------------------------------
![gradle_error](https://cloud.githubusercontent.com/assets/10733085/16623021/dd47a7b0-4361-11e6-8f88-ee9dc332950e.JPG)

**Comment by ISchwarz23** [comment]
In 'repositories' you state 'mavenCentral()' but this library is on JCenter. So you could add 'jcenter()' or replace 'mavenCentral()' by it.

**Comment by sdutta9** [comment]
Getting the same error even after replacing mavenCentral() with jcenter().

**Comment by ISchwarz23** [comment]
Could you please post the content of the build.gradle in your root folder?

**Comment by sdutta9** [comment]
Below is my complete build.gradle file in root folder:
--------------------------------------------------------------------------------------------------------------------------
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by ISchwarz23** [comment]
Do you see an error, if you execute a clean of your project?

**Comment by ashorekumar** [comment]
I resolved this issue by adding 

maven { url "http://jcenter.bintray.com"}
