### ISSUE TITLE
Cannot find a way to add label headers when extending TableDataAdapter

### ISSUE THREAD

**Issue by rubin-parakhi** [ISchwarz23/SortableTableView#40]
Added the required Data to the Table along with adding elevation and adding color but could not find a way to add the header to the TableDataAdapter. Help!!!!

**Comment by ISchwarz23** [comment]
Hi @rubin-parakhi 

I'm not sure, if I understood corectly what you are trying to achive. You try do display column headers in your table by using the SimoleTableHeaderAdapter?

Best regards,
Ingo

**Comment by joemackay** [comment]
Is is possible to place other views such as TextViews etc next to the TableView or does it command ownership of the screen like a ListView does. My Relative layout has a TextView at the top and Tableview right after it. Now the tableView has a very long list and cannot scroll. 

Joe

**Comment by ISchwarz23** [comment]
Hi @joemackay,

for the next time, please create a seperate issue for your questions. 
In your case the issue is in the layout file. Your `LinearLayout` and `TableView` have the height `wrap_content`, so they will grow to wrap the complete tableview data content. This is why the tableview is very long and there is no scrolling. I would get comletely rid of your linear layout and do it like this:

```xml
<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.xxx.app.xxx.src.CourseDetailsFragment"
    android:background="@color/body_readable_bg"
    android:id="@+id/course_details">
    
    <TextView
        android:id="@+id/course_title"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:textAppearance="?attr/textAppearanceListItem"
        android:textSize="16sp"
        android:textStyle="bold"
        android:layout_marginTop="10dp"/>

    <de.codecrafters.tableview.TableView
        xmlns:table="http://schemas.android.com/apk/res-auto"
        android:id="@+id/instTableView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/course_title"
        android:layout_marginTop="10dp"
        android:divider="@color/list_divider"
        android:dividerHeight="1dp"
        android:textSize="@dimen/ten_dp" />

</RelativeLayout>
```

**Comment by rubin-parakhi** [comment]
Hi there,
I used your library and tried to implement the table but couldn't display
the header section using tableadapter. No way to add header like in
sortable adapter

**Comment by ISchwarz23** [comment]
Did you have a look to the sample application? If yes and it is still not working I can only help you, if you share your code.
