### ISSUE TITLE
Divider for data and header row elements 

### ISSUE THREAD

**Issue by Ulop** [ISchwarz23/SortableTableView#41]
Hello! Can you add methods like this?
setDataRowElementDividerHeight()
setDataRowElementDividerColor()
setHeaderRowElementDividerHeight()
setHeaderRowElementDividerColor()

**Comment by ISchwarz23** [comment]
Hi @Ulop,

I guess you know that there is a way to set the data row divider height and color via xml:
```xml
    <de.codecrafters.tableview.TableView
        android:id="@+id/tableView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:divider="@color/black"
        android:dividerHeight="1dip"
        ...  /> 
```
So you need to set this during runtime? I also want to get sure, that we have the same understanding of the header row element divider. How does the header row element look like in your opinion?

**Comment by Ulop** [comment]
Hi @ISchwarz23 
Your code is way to set divider between rows in tableview. But I'm need a divider elements in row on this 
[rowView](https://github.com/ISchwarz23/SortableTableView/blob/master/tableview/src/main/java/de/codecrafters/tableview/TableDataAdapter.java#L148) and on TableHeaderView(extends LinearLayout)

**Comment by ISchwarz23** [comment]
Hi Alex,
so you need some vertical lines between the cells in one row (data as well as header row)?
Best regards,
Ingo

**Comment by Ulop** [comment]
Hi @ISchwarz23
Yes, that's it
