### ISSUE TITLE
Scroll-able along with other items, outside it's container

### ISSUE THREAD

**Issue by joemackay** [ISchwarz23/SortableTableView#42]
Hello, 
Thank you for the swift reply to my question. I've opened it as a new issue as you advised.
I tried the syntax as you requested. It works well, though a small bit still bugs me. So I enclosed it in a scrollview but it still scrolls inside itself.

The structure of my layout file
` 
ScrollView  xmlns:android="http://schemas.android.com/apk/res/android"
android:layout_width="match_parent" android:layout_height="match_parent">

	<LinearLayout>  header views like instructions, etc </LinearLayout>
	
        <de.codecrafters.tableview.TableView
            xmlns:table="http://schemas.android.com/apk/res-auto"
            android:id="@+id/instTableView"
            android:orientation="vertical"
            android:layout_marginTop="10dip"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:divider="@color/list_divider"
            android:dividerHeight="1dip"
            android:textSize="10sp"
            android:layout_marginBottom="50dp"
            android:background="@drawable/flat_border_set"
            android:gravity="center_horizontal"/>
	//Long list of item views {table rows}
	
	<LinearLayout> - footer views eg share buttons etc </LinearLayout>
</ScrollView`

As it is, when I scroll down the rows scroll within the table container. This becomes a challenge for smaller screens.

So, I'd like to have the whole page to scroll so that if a user scrolls down, the table view scrolls along with everything else. Am I doing it wrong?

Joe

**Comment by ISchwarz23** [comment]
Hi Joe,

first I would like to be sure, that I understood you correctly. You want to use the TableView together with other views in a LinearLayout. (Some views before the TableView and some views after.) You don't want the TableView to scroll, but to show it's full content. Therefore you have your LinearLayout inside a ScrollView. Is this all correct?

Best regards,
Ingo

**Comment by joemackay** [comment]
Yes, that's correct. Spot on. More like a Listview that scrolls along with other elements of the page. I have placed other views in the header LinearLayout and some footer views in another Layout at the bottom. If I give the TableView a fixed height then it performs well and scrolls along with other items. But fixed height is definitely not the right approach.

**Comment by ISchwarz23** [comment]
Hi Joe,

as you said fixed size is working for this approach. As the TableView is using an `ListView` internally you have the known issues for `WRAP_CONTENT` so you should not do this.
So if you really want to have the described UI (also if I would recommend to re-think this, as it is not optimal for small screens) I would calculate the table height using the number of rows in the `TableView` and set this value as fixed size.  
Hope this helps you.
