### ISSUE TITLE
Support for Android SDK <11.

### ISSUE THREAD

**Issue by joemackay** [ISchwarz23/SortableTableView#43]
Do you plan to release a version compatible with Android SDK lower than 11. This has locked out 20% of potential users. Alternatively, what would you advise I do if need the compatibility?

Thank you.

Joe

**Comment by ISchwarz23** [comment]
Hi Joe,

I just had a look on platform section of the (Developer Dashboard)[https://developer.android.com/about/dashboards/index.html#Platform] and it looks like you only miss 2 percent of all devices (April 2016). But to answer your question: I have not planned to support the versions < 11.

**Comment by joemackay** [comment]
Alright, thank you for the correction. I enjoy using the library, it has improved my work a lot

**Comment by ISchwarz23** [comment]
Thank you! I'm very pleased to hear that!
