### ISSUE TITLE
Findviewbyid return null

### ISSUE THREAD

**Issue by TonyStarkk** [ISchwarz23/SortableTableView#5]
Hello,

When i try to get sortabletableview it return me Null, i'm using it in fragment.

`materiauTableView = (SortableMateriauTableView) view.findViewById(R.id.tableView);`
```
<com.diadecmobile.view.fragment.projectFragment.materiauxFragment.SortableMateriauTableView
        android:id="@+id/tableView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        custom:columnCount="8"
        custom:headerElevation="10"
        custom:headerColor="@color/theme_primary" />
```

**Comment by ISchwarz23** [comment]
As I can't reproduce this issue I think that this is not an issue of the TableView but the usage of it. Returning null usually means, that Android is not able to find the View with the given ID inside the View where you are trying to find it. So maybe you are accidently search inside a view, which does not contain the TableView.

So I am speaking about the `view` in this line of code:
```java
materiauTableView = (SortableMateriauTableView) view.findViewById(R.id.tableView);
```
