### ISSUE TITLE
Possible to use SearchView to search SortableTableView

### ISSUE THREAD

**Issue by Albean** [ISchwarz23/SortableTableView#50]
Hi,

I really like your SortableTableView, is it possible to use it alongside SearchView in the Toolbar?

**Comment by ISchwarz23** [comment]
Hi @Albean,

of cause you can. All you have to do is filter the data of your TableDataAdapter. The most easy way to do this will be to make your TableDataAdapter implementing the Filterable interface. Have a look to [this example](https://coderwall.com/p/zpwrsg/add-search-function-to-list-view-in-android) which is about a ListView, but the same concept can be applied to the TableView and SortableTableView.
