### ISSUE TITLE
Adding Header Text.

### ISSUE THREAD

**Issue by Albean** [ISchwarz23/SortableTableView#51]
Hi ,

Im trying to add text to the header but failing.
How can it be done?

 What i have tried,

 TableView<String[]> tableView = (TableView<String[]>) getView().findViewById(R.id.view12);
        tableView.setHeaderBackground(R.color.accent);
      SimpleTableHeaderAdapter simpleTableHeaderAdapter = new SimpleTableHeaderAdapter(container,false, R.string.id, R.string.alarm, R.string.Add);
       tableView.setHeaderAdapter(simpleTableHeaderAdapter);

**Comment by ISchwarz23** [comment]
Hi @Albean,

I wonder about the parameters you pass to the SimpleTableHeaderAdapter. Seems like you are passing a Boolean where an Integer is expected. Could this be the issue?

Best regards,
Ingo

**Comment by ISchwarz23** [comment]
Closed because there was no feedback after more than 3 monthes.
