### ISSUE TITLE
FloatingActionButton

### ISSUE THREAD

**Issue by LiRenYun** [ISchwarz23/SortableTableView#52]
I find i use the this and can't build the project when i had use FloatingActionButton

the Error show:
Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering

java.lang.RuntimeException: Unable to start activity ComponentInfo{beans.physicalfitness/beans.physicalfitness.MainActivity}: android.view.InflateException: Binary XML file line #26: Error inflating class android.support.design.widget.FloatingActionButton

thanks

**Comment by ISchwarz23** [comment]
Hi @LiRenYun,

I have created an example with a FAB. It was working without any issues. As the SortableTableView is depending on the latest version of the `appcompat-v7`. Currently it depends on the version `24.2.0`. Could you please check which version of the `appcompat-v7` as well as the version of `design` you are using? I have tried it successfully with the version `24.2.0`.

Best regards,
Ingo
