### ISSUE TITLE
How to give vertical column separator for rows and header?

### ISSUE THREAD

**Issue by ahmadalibaloch** [ISchwarz23/SortableTableView#56]
I can't find a way to give vertical separator for columns in a row or for the header row.

**Comment by ISchwarz23** [comment]
Hi Ahmad,

this feature is not available yet, but there is already a push request sent by @Ulop that exactly fixes your issue. As soon I have merged and adapted it, the feature will be available.

Best regards,
Ingo

**Comment by ISchwarz23** [comment]
By the way, as you are a hight frequent user of this library, it would be nice if you list the apps where you have used this library to the issue https://github.com/ISchwarz23/SortableTableView/issues/35 :)

**Comment by ISchwarz23** [comment]
Duplicate to #125
