### ISSUE TITLE
Giving border to Header view is not possible

### ISSUE THREAD

**Issue by ahmadalibaloch** [ISchwarz23/SortableTableView#57]
If I set background color of Header view to same as the screen background then it doesn't look like a table because you can't give border to header views. 

There should be a way to give border to all table too. I am using this table for a pdf generation (print view) where I need white background (black and white) but without border its not a table any more :(

There is also no vertical separator for row columns or header view column. I also created a separate issue for this. https://github.com/ISchwarz23/SortableTableView/issues/56

**Comment by Ulop** [comment]
Table in my fork of this library look like this
but it based on old source code
![table_screen](https://cloud.githubusercontent.com/assets/3891063/19465380/6ba94b3e-950c-11e6-8666-29048695fc4a.png)
source:
[tableview.zip](https://github.com/ISchwarz23/SortableTableView/files/535339/tableview.zip)

**Comment by ISchwarz23** [comment]
For your use-case I would give a black background to the header and turn the font color to white so it can be distinquished from the data rows.  
Nevertheless there will be a change to set a drawable as header background (instead of the color) so it'll fit all use-cases (e.g. having a border around the header).

**Comment by ahmadalibaloch** [comment]
I need to print a black and white paper. White background, of course, and black text.

**Comment by ISchwarz23** [comment]
This means the PDF library you're using is not able to handle white font on black background?

**Comment by ahmadalibaloch** [comment]
No. It means I really need borders of black color for black text in columns with a white background. :-)

**Comment by ISchwarz23** [comment]
Hi Ahmad,

I am very glad to tell you, that there is already a possibility in the TableView to achive what you need to do (as you have recognized, I don't want to provide a method to set a border for the header, as I think this is a very rare use-case).  
So, to have the requested border for the header, you can set a drawable as header background. In your case this should be a white rectangle with a black border. Here is the drawable that I used for testing:
```xml
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
       android:shape="rectangle">
    <solid android:color="#ffffff"/>
    <stroke
            android:width="2px"
            android:color="#000000"/>
</shape>
```
Simply set this shape as header background using `TableView#setHeaderBackground`... et voilà!  
  
PS: Nevertheless, the column seperation will be introduced for sure!

**Comment by ulaserdegor** [comment]
@Ulop How did you Border line all cell

**Comment by ulaserdegor** [comment]
@Ulop  how did you borderline all table?

**Comment by Ulop** [comment]
@ulaserdegor At the moment I do not have access to the source code for that project, where the screen comes from. So I can not say for sure. Most likely they were left or right drawables for cells, divider for listview items for rows and custom header.
Also you can see this repo
https://github.com/evrencoskun/TableView
in @evrencoskun repo table based on recyclerview
