### ISSUE TITLE
Could add the editText view in the table?

### ISSUE THREAD

**Issue by LiRenYun** [ISchwarz23/SortableTableView#58]
I want to design the table that has the input view, Could the SortableTableView do that?
Thanks~!

**Comment by ISchwarz23** [comment]
Hi @LiRenYun,. 
  
of cause it is possible (but from UX point of view I would not recommend it). All you need to do is implement your custom `TableDataAdapter`. If you need an example how this is done, have a look at the example app in this repository to see the CarTableDataAdapter.
  
Best regards,. 
Ingo

**Comment by LiRenYun** [comment]
Thanks for your help,and I try to change the CarTableDataAdapter and add the column and table_cell_input.xml,but when I slip down or up the table,the EditText's value will be disapear.
How could I deal with this problem and get the value that in EditText View.

This photo is my changing:
https://imgur.com/gallery/McUiP

Thank you very much~

**Comment by ISchwarz23** [comment]
This is, because you read the weight from the car and set it to the `EditText` via `car.getWeight();`. When the user changes this value you have to write it back to the model via `car.setWeight( newWeight );` else it will get the old value again from the model (which is in your case empty).

**Comment by LiRenYun** [comment]
HI~ @ISchwarz23 
Thanks for your help 
I finally finished it :D !!!
Thank you again~~!!!

**Comment by jawherjouini** [comment]
Hi ISchwarz23, thank you for this amazing work.
I tried to implement an EditText inside the tableAdpater as you recommended here, but I faced an issue with the long click as the listener becomes working only over the edittext and the method "onDataLongClicked" is fired twice.
Could you help me please ?

**Comment by ISchwarz23** [comment]
Hi @jawherjouini,
could you please explain, what you are trying to implement and how the current state differs from it?
Best regards,
Ingo

**Comment by jawherjouini** [comment]
Hi, thanks for the quick reply,
in your example CarTableAdapter, I did this to renderProducerLogo : 

private View renderProducerLogo(final Car car, final ViewGroup parentView) {
        //final View view = getLayoutInflater().inflate(R.layout.table_cell_image, parentView, false);
        //final ImageView imageView = (ImageView) view.findViewById(R.id.imageView);
        final EditText imageView = new EditText(getContext());
        //imageView.setImageResource(car.getProducer().getLogo());
        return imageView;
    }

And the DataLongClick event is no longer fired in the other columns but only when you long click on the Edittext

**Comment by SaeedZhiany** [comment]
I have a serious problem.
I create a CustomTableDataAdapter that extends from your `TableDataAdapter` and in `getDefaultCellView` I retrun and EditText.
when run my app and click on the editText, its focus immediately has been removed and keyboard disappears. what can I do?
