### ISSUE TITLE
How to colorize the divider?

### ISSUE THREAD

**Issue by DragonSpirit** [ISchwarz23/SortableTableView#6]
Hello! Does library can colorize divider or make it transperent?
 android:divider and .setDividerDrawable won't work at all
Thanks!

**Comment by ISchwarz23** [comment]
Hi DragonSpirit,   
your issue is a good point. It is infact a missing feature which is now available in the new version 0.9.6. It supports now the adaptation posibilities like the ListView via the layout file. To use it just update your dependency to the new version.   

    dependencies {
        compile 'de.codecrafters.tableview:tableview:0.9.6'
        ...
    }

**Comment by ahmadalibaloch** [comment]
How do you actually add a divider for rows of your choice color? I give color to rows based on my business logic. Now there are some rows with same color. I need a divder of 1dp at the bottom of each row view.

**Comment by ISchwarz23** [comment]
You can do so by specifying `divider` and `dividerHeight` in the layout xml. Se this example:

```xml
<de.codecrafters.tableview.TableView
    android:id="@+id/tableView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:divider="@color/black"
    android:dividerHeight="1dip"
    ...  />  
```

**Comment by ahmadalibaloch** [comment]
Why the documentation is not complete, like for example the case of divider. I have been searching for minutes. Thanks for the information too, it works. :+1:

**Comment by ISchwarz23** [comment]
No, unfortunatelly there is no programatical way to do so. But the documentation will be extended with the divider xml tags.
