### ISSUE TITLE
Why I use it works on Android5.0.2 ,but doesn't works on Android6.0  ,some data will be hide and some fragment can't work on scroll?

### ISSUE THREAD

**Issue by d6255299** [ISchwarz23/SortableTableView#60]

**Comment by ISchwarz23** [comment]
Hi @d6255299 ,

could you please describe how the described behavior can be reproduced? Or show at least some screenshots that foster your statement?

Best regards,
Ingo

**Comment by SheikhZayed** [comment]
doesnt work on android 6,what could be the problem ?

**Comment by ISchwarz23** [comment]
Duplicate of #70
