### ISSUE TITLE
Column Values Sum

### ISSUE THREAD

**Issue by ulaslaslas** [ISchwarz23/SortableTableView#62]
Hi again :) 
I have a suggestion. A row that calculates the sum of columns with number values can be added.

Like this 
![image](https://cloud.githubusercontent.com/assets/12948351/20483335/1f82da50-affa-11e6-872c-348d752926ad.png)

**Comment by ISchwarz23** [comment]
Hi @ulaslaslas,

yes, but then this row should be outside the table, cause otherwise it will be reorderd on sorting like any other row.

**Comment by ulaslaslas** [comment]
You are right. @ISchwarz23 
i solved problem by adding different layout :)

thanks again!
![screenshot_1479794219](https://cloud.githubusercontent.com/assets/12948351/20512657/733bab74-b089-11e6-90f9-0964643d321e.png)
