### ISSUE TITLE
i can't sort my table 

### ISSUE THREAD

**Issue by ryodoo** [ISchwarz23/SortableTableView#63]
Hi,
I'm a beginner in SortableTableView i went just show a table with filter I have all ok but when I click to sort my table nothing change this is my code

`public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        view= inflater.inflate(R.layout.fragment_feuille, container, false);
        String[][] clients = new String[500][50];

        for (int i = 0; i < Variable_general.json_feuille_route.length(); i++) {
            JSONObject jo = null;
            try {
                jo = Variable_general.json_feuille_route.getJSONObject(i);
                String[] client = new String[] { jo.getString("id"), jo.getString("name"),
                        jo.getString("type"), jo.getString("category") };
                clients[i]=client;
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }
        SortableTableView sortableTableView = (SortableTableView) view.findViewById(R.id.tableView);
        TableColumnWeightModel columnModel = new TableColumnWeightModel(4);
        columnModel.setColumnWeight(1, 2);
        columnModel.setColumnWeight(2, 2);
        sortableTableView.setColumnComparator(0, new CarProducerComparator());
        sortableTableView.setColumnComparator(1, new CarProducerComparator());
        sortableTableView.setColumnComparator(2, new CarProducerComparator());
        sortableTableView.setColumnComparator(3, new CarProducerComparator());
        sortableTableView.setHeaderAdapter(new SimpleTableHeaderAdapter(FeuilleFragment.this.getActivity(),"id","name","Type","Spicialité"));
        sortableTableView.setColumnCount(4);
        sortableTableView.setDataAdapter(new SimpleTableDataAdapter(FeuilleFragment.this.getActivity(), clients));
        return view;

    }

    private  class CarProducerComparator implements Comparator<String> {
        @Override
        public int compare(String car1, String car2) {
            Toast.makeText(FeuilleFragment.this.getActivity(), " id :  name ! ", Toast.LENGTH_LONG).show();
            return car1.compareTo(car2);
        }
    }`
My output 

![2016-11-29_173334](https://cloud.githubusercontent.com/assets/9296498/20721267/2eb5909c-b65a-11e6-90c2-bfc05ef0ea89.jpg)

**Comment by ISchwarz23** [comment]
Hi @ryodoo,

there are two mayor issues in your code snipped. First the sorting issue you mentioned. The reason for this is the `Comparator` you set. This is a `Comparator` for `String`s, but as your data objects are of type `String[]` this should be a `Comparator<String[]>`.
To avoid such issues you should use the `SortableTableView` with correct generic. In your case this would be 
```java
SortableTableView<String[]> sortableTableView = (SortableTableView<String[]>) view.findViewById(R.id.tableView);
```
In general I recommend to have your own data type instead of an array of primitives, like
```java
SortableTableView<Client> sortableTableView = (SortableTableView<Client>) view.findViewById(R.id.tableView);
```

The second issue is that you create a `TableColumnModel` but you do not set it to the `TableView`. This is why the columns in your screenshot have all the same width.

Best regards,
Ingo
