### ISSUE TITLE
How i can put button in SortableTableView

### ISSUE THREAD

**Issue by ryodoo** [ISchwarz23/SortableTableView#64]
Hello,
I want to have for each client a button in which I can test a deferent operation for each case, I do not want to use TableDataClickListener because it will be used for another processing

its my code 

`public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        view= inflater.inflate(R.layout.fragment_feuille, container, false);
        String[][] clients = new String[Variable_general.json_feuille_route.length()][];

        for (int i = 0; i < Variable_general.json_feuille_route.length(); i++) {
            JSONObject jo = null;
            try {
                jo = Variable_general.json_feuille_route.getJSONObject(i);
                String[] client = new String[] {jo.getString("name"),
                        jo.getString("type"), jo.getString("category"),"Button" };
                clients[i]=client;
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }
        SortableTableView<String[]> sortableTableView = (SortableTableView<String[]>) view.findViewById(tableView);
        sortableTableView.setColumnComparator(0, new ClientNameComparateur());
        sortableTableView.setColumnComparator(1, new ClientTypeComparateur());
        sortableTableView.setColumnComparator(2, new ClientSoicialiteComparateur());
        sortableTableView.setHeaderAdapter(new SimpleTableHeaderAdapter(FeuilleFragment.this.getActivity(),"Nom","Type","Spicialité","Action"));
        sortableTableView.setColumnCount(4);
        sortableTableView.setDataAdapter(new SimpleTableDataAdapter(FeuilleFragment.this.getActivity(), clients));
        sortableTableView.addDataClickListener(new CarClickListener());
        return view;

    }

    private  class setButton  {
        public Button getButton(String[] client) {
            Button btn = null;
            if (client[1].equals("test")) {
                btn = new Button(getActivity());
                btn.setText("In home");
                btn.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        Toast.makeText(getActivity(),"In home",Toast.LENGTH_SHORT).show();
                    }
                });
            } else {
                btn = new Button(getActivity());
                btn.setText("Out home");
                btn.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        Toast.makeText(getActivity(),"Out home",Toast.LENGTH_SHORT).show();
                    }
                });
            }

            return btn;
        }
    }

    private class CarClickListener implements TableDataClickListener<String[]> {
        @Override
        public void onDataClicked(int rowIndex, String[] clickedCar) {
            String clickedCarString = clickedCar[0] + " " + clickedCar[1];
            Toast.makeText(getContext(), clickedCarString, Toast.LENGTH_SHORT).show();
        }
    }

    private  class ClientNameComparateur implements Comparator<String[]> {
        @Override
        public int compare(String[] car1, String[] car2) {
            return car1[0].compareTo(car2[0]);
        }
    }
    private  class ClientTypeComparateur implements Comparator<String[]> {
        @Override
        public int compare(String[] car1, String[] car2) {
            return car1[1].compareTo(car2[1]);
        }
    }
    private  class ClientSoicialiteComparateur implements Comparator<String[]> {
        @Override
        public int compare(String[] car1, String[] car2) {
            return car1[2].compareTo(car2[2]);
        }
    }`
![2016-11-30_024355](https://cloud.githubusercontent.com/assets/9296498/20737999/03cc8932-b6a8-11e6-8e9b-1a6d12a8c959.jpg)

**Comment by ISchwarz23** [comment]
Hi again,

to have a `Button` inside you `TableView` instead of simple `TextView`s, you have to create your own `TableDataAdapter`. This allows you to return anything of type `View` for a cell. 

If there you have trouble to create souch a `TableDataAdapter` just ask.

Best regards,
Ingo

**Comment by ryodoo** [comment]
Hi,
Thanks but I do not know how to implement is what I can have an exmple

**Comment by ISchwarz23** [comment]
To implement you custom `TableDataAdapter` you have to extend it from the `TableDataAdapter` and implement the `getCellView(int rowIndex, int columnIndex, ViewGroup parentView)` method.

Here an example for your ClientTableDataAdapter:
```java
public class ClientTableDataAdapter extends TableDataAdapter<String[]> {

    // ...

    public View getCellView(int rowIndex, int columnIndex, ViewGroup parentView) {
        final String[] client = getRowData(rowIndex);
        View renderedView = null;

        switch (columnIndex) {
            case 0:
                renderedView = renderTextView( client[0] );
                break;
            case 1:
                renderedView = renderTextView( client[1] );
                break;
            case 2:
                renderedView = renderTextView( client[2] );
                break;
            case 3:
                renderedView = renderButton( client[3] );
                break;
        }

        return renderedView;
    }

    private Button renderButton( String label ) {
        Button button = new Button( getContext() );
        button.setText( label );
        return button;
    }

    private View renderTextView( String label ) {
        TextView textView = new TextView( getContext() );
        textView.setText(value);
        return textView;
    }

    // ....

}
```
