### ISSUE TITLE
How to set header height

### ISSUE THREAD

**Issue by EgyptianM** [ISchwarz23/SortableTableView#65]
Hi,
Thank you for this great library.

I'm having issues with the header because it's height is taking too much space of the screen and I noticed that in the example too.

I searched Readme and the example for any method to control header height but I didn't find.

Can you please tell me how to set header height?

Best Regards
Mohammad

**Comment by ISchwarz23** [comment]
Hi Mohammad,

which `TableHeaderAdapter` are you currently using. The `SimpleTableHeaderAdapter` or a custom one?

Best regards,
Ingo

**Comment by EgyptianM** [comment]
Hi Ingo,
I'm using SimpleTableHeaderAdapter.

**Comment by ISchwarz23** [comment]
If you are using the `SimpleTableHeaderAdapter` you can use the methods...
- setPaddingLeft(final int paddingLeft)
- setPaddingTop(final int paddingTop)
- setPaddingRight(final int paddingRight)
- setPaddingBottom(final int paddingBottom)
- setTextSize(final int textSize)
- setTypeface(final int typeface)
- setTextColor(final int textColor)  

... to modify the look of your table header.

**Comment by EgyptianM** [comment]
Yes I know these methods but I want to decrease header height like
`setHeight(int height)`
Can you add it please?

Thank you.

**Comment by ISchwarz23** [comment]
I would avoid it because if there would be a method like this, I have to define a behaviour of the header, if the header views inside are bigger or smaller than the defined header. And most likely not all users if this library will need the same behavior and this will result in a big amount of issues.  
So if you simply set the padding on top and bottom to 0 (default is 30), your header will shrink as it is wrapping it's content.

**Comment by EgyptianM** [comment]
Thank you very much.
Yes this what happened.
Have a nice day.

**Comment by immosk** [comment]
Hi, 

I have some problem with setting the height of row too. But I use a custom adapter (not `SimpleTableDataAdapter`). How to set height of row in my case? Thanks in advance

**Comment by ISchwarz23** [comment]
Hi,

the height oft your row is defined by the height of the highest cell inside your row. So simply add some margin to the views created in your custom adapter.

Best regards,
Ingo

**Comment by asr1994** [comment]
Hi,
how can i set typeface for headers and cell? i have a .ttf file in my assets folder and i want to use it for cells and header but i don't know how it is possible.
please help me, thank you very much!
