### ISSUE TITLE
how to sort table programtically?

### ISSUE THREAD

**Issue by EgyptianM** [ISchwarz23/SortableTableView#67]
Hi Igno,

I want to show the table for the first time sorted based on certain column either ASC or DESC.

Is this possible in code or in xml?

**Comment by ISchwarz23** [comment]
Hi @EgyptianM,

Use the methode sort(final int columnIndex, final boolean sortAscending) after setting your TableDataAdapter and the Comparator for the specific column.

Best regards,
Ingo

**Comment by EgyptianM** [comment]
Thank you very much
