### ISSUE TITLE
Header Text and Sort Indicators Not Shown on API 16 or 17

### ISSUE THREAD

**Issue by DanStout** [ISchwarz23/SortableTableView#70]
Unfortunately I don't have any physical devices running these versions of Android, so I'm not able to test whether the problem is somehow related to running in the emulator. The problem isn't present API 18 (4.3) or above (which I've tested both physically and virtually).

I removed all modifications to the color/styling, and the problem still persists. The header has the usual height and width, but it is as if there are simply no columns:

![blurred](https://cloud.githubusercontent.com/assets/6951039/20901793/91f5defa-bb0a-11e6-9c27-015dec3c94d3.png)

In the constructor of my subclass of `SortableTableView`, I set the header adapter as follows:

```
SimpleTableHeaderAdapter header = new SimpleTableHeaderAdapter(context, /* omitted */);
setHeaderAdapter(header);
```
The XML for the table view is:

```
</*package*/.TransactionsTableView
	android:id="@+id/trans_table"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	app:tableView_columnCount="4"
	/>
```

Do you know of any issues with the library on these versions of Android?

Edit 1: It looks like this may be related to my previous bug report. The headers are only invisible when they are created while the view is initially hidden - so the sample app worked fine on APIs 16 & 17. I also copied my table into a plain activity with no fragments-and-viewpager going on, and the headers worked there as well.

Edit 2: Here is my hacky workaround to invalidate the header when the fragment becomes visible:

```
@Override
public void setMenuVisibility(boolean menuVisible)
{
	super.setMenuVisibility(menuVisible);
	if (menuVisible && Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN_MR2)
	{
		try
		{
			Field f = SortableTableView.class.getDeclaredField("sortableTableHeaderView");
			f.setAccessible(true);
			LinearLayout header = (LinearLayout) f.get(mTableView);
			header.invalidate();
		}
		catch (NoSuchFieldException e)
		{
			e.printStackTrace();
		}
		catch (IllegalAccessException e)
		{
			e.printStackTrace();
		}
	}
}
```

**Comment by frodberserk** [comment]
Having same issue. The header got just background and no text.
![screenshot_22](https://cloud.githubusercontent.com/assets/5646747/21013815/64a6dcb4-bd81-11e6-842d-b5f1a7690085.png)

**Comment by ISchwarz23** [comment]
Which version of the table view and such android version are you using?

**Comment by DanStout** [comment]
I'm using TableView 2.4.1, and have observed the issue on API 16 (Android 4.1) and API 17  (Android 4.2).

**Comment by frodberserk** [comment]
I'm also using 2.4.1 and I got this on my Nexus 5 with version 6.0.1.

**Comment by tracerTres** [comment]
I'm also having the same issue.
TableView Version: 2.4.1
API: 16 and 23

**Comment by tracerTres** [comment]
The problem seems to be with the line https://github.com/ISchwarz23/SortableTableView/blob/master/tableview/src/main/java/de/codecrafters/tableview/TableHeaderView.java#L74
When getWidth() is called the layout has not been done hence the width returned is 0.

Adding the LayoutChangeListender on https://github.com/ISchwarz23/SortableTableView/blob/master/tableview/src/main/java/de/codecrafters/tableview/TableHeaderView.java#L39
should somehow fix this but for some reason it's not working.

The workaround that has worked for me is setting the header adapter inside the GlobalLayoutListener


```
mTableView = (TableView<String[]>) view.findViewById(R.id.tableView);
ViewTreeObserver vto = mTableView.getViewTreeObserver();
        vto.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                mTableView.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                mTableView.setHeaderAdapter(mSimpleTableHeaderAdapter);
            }
        });
```

**Comment by ISchwarz23** [comment]
Thanks @tracerTres! This will help me during my investigations.

**Comment by zh1992** [comment]
Thanks @tracerTres !  However, the screen causes dithering.

**Comment by ISchwarz23** [comment]
Hi @all,

please try to reproduce this issue with the new TableView version 2.4.2. I was not able to see this issue anymore using emulators with api 16, 18, 21, 25.

Best regards,
Ingo

**Comment by tracerTres** [comment]
Hi @ISchwarz23 
The issue I was having does not appear when using the new version.
I am curious to know what the problem was, since after going through the changes in the new version, I see no changes (or maybe I missed something) directly touching on the issue I was having.
