### ISSUE TITLE
Some rows doesn't fire TableDataClickListener

### ISSUE THREAD

**Issue by EgyptianM** [ISchwarz23/SortableTableView#71]
Hi,

There are some rows in the table which doesn't fire TableDataClickListener when I click on them.
Some not all of them which means that the TableDataClickListener is working for some rows and not for other rows.
Can you guide me to solve this issue?

Thank you.

**Comment by ISchwarz23** [comment]
Hi,

I'm not able to help you without knowing your implementations. Can you share your code?

Best regards,
Ingo
