### ISSUE TITLE
Fix first column, and other columns could scroll horizontally

### ISSUE THREAD

**Issue by browningweb** [ISchwarz23/SortableTableView#72]
Thanks for your great library,

I have a problem. in my situation I have tables with 10+ columns, I really need to have a horizontal scroll for it and also making more width for each column. And fix the first column like excel. is there anyway to do that?

Thanks.

**Comment by ISchwarz23** [comment]
Hi @browningweb,

you can add your table to a `HorizontalScrollView`. In addition you can use the `TableColumnDpWidthModel` to set the collumn width.  
Unfortunatelly it is not possible to fix the first column. Maybe this will come in a future version of the `SortableTableView`, but till now it is not plannded.

Best regards,
Ingo

**Comment by sirajsolutelabs** [comment]
Hi @ISchwarz23,

I want to create dynamic table like this with data from JSON. In that dynamically as many columns will come and set. I tried setting columnCount to 10 and TableColumnPxWidthModel to 300 for each column. But whenever I tried to set HorizontalScrollView around SortableTableView, the view is no more visible. Can you please have a look at the code:

<HorizontalScrollView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/toolbar">

        <de.codecrafters.tableviewexample.SortableCarTableView
            android:id="@+id/tableView"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            custom:tableView_columnCount="10"
            custom:tableView_headerColor="@color/primary"
            custom:tableView_headerElevation="0" />
    </HorizontalScrollView>

**Comment by tracerTres** [comment]
Hi @sirajsolutelabs 
Have you tried changing `android:layout_width="wrap_content"` to `android:layout_width="match_parent"` in your SortableCarTableView

**Comment by sirajsolutelabs** [comment]
@tracerTres : Thanks It worked.

**Comment by TechnoTrancer** [comment]
It works, but doesn't feel good cause the Vertical scroll, will work best with internal horizontal scroll

**Comment by sirajsolutelabs** [comment]
For everyone who stucked in scrolls:

In the library, @ISchwarz23  has used Listview to display the body. So Listview will only works for Vertical scrolling. After taking horizontal Scrollview around sortableTableView doesn't solve the problem as both the scrolls conflict each other and cause horrible result. @TechnoTrancer : Use this code to make scroll efficient:

`<HorizontalScrollView
        android:id="@+id/hv_scroll"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <com.intellimind.assistance.goals.table.SortableGoalsTableView
            android:id="@+id/tableView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:nestedScrollingEnabled="true"
            custom:tableView_headerColor="@color/dark_gray"
            custom:tableView_headerElevation="0" />
    </HorizontalScrollView>`

**Comment by TechnoTrancer** [comment]
Oh thank you @sirajsolutelabs , it works much better

**Comment by sirajsolutelabs** [comment]
You welcome @TechnoTrancer.
Yes it worked for lollipop or newer device. I am still looking for the older versions. Let me know if you find one.
