### ISSUE TITLE
Following example give me an error

### ISSUE THREAD

**Issue by Pascal66** [ISchwarz23/SortableTableView#77]
With 
final AccountAdapter accountAdapter = new AccountAdapter(mCtx, ListOf, sortableView);
And in AccountAdapter : 
```
public AccountAdapter(Context context, List<ScalpingStrategy.Playing> data, final TableView<ScalpingStrategy.Playing> tableView) {
            super(context, data, tableView);
        }
```
Cannot resolve

Because of : Candidat are :
TableDataAdapter(Context, Playing[])   TableDataAdapter(Context, List<Playing>)   TableDataAdapter(Context, int, List<Playing>)   TableDataAdapter(Context, TableColumnModel, List<Playing>)

**Comment by ISchwarz23** [comment]
Hi @Pascal66,

from your AccountAdapter you are calling the constructor of the TableDataAdapter with parameters of type Context, List, TableView. But as you can see, there is no constructor taking these arguments.  
You can fix this issue by removing the last argument. This will match the TableDataAdapter(Context, List) constrictor.

Best regards,
Ingo

**Comment by Pascal66** [comment]
thank you
