### ISSUE TITLE
How to handle dynamic sorting using Comparator

### ISSUE THREAD

**Issue by sirajsolutelabs** [ISchwarz23/SortableTableView#78]
I have implemented your library in my application. I have the rows and columns with dynamic values. I populated rows and columns with header successfully. But how to manage dynamic sorting using comparator. Because in your example you have focused mainly on static comparison of columns.

**Comment by ISchwarz23** [comment]
Hi,

could you explain in more detail what you mean with dynamic sorting?

Best regards,
Ingo

**Comment by sirajsolutelabs** [comment]
Sure, I have the JSON response in which I am getting headers and body of table. In that I populated headers and body in the table:

`String[] myarray = new String[goalData.getTableheaderList().size()];
        for (int i = 0; i < goalData.getTableheaderList().size(); i++) {
            myarray[i] = goalData.getTableheaderList().get(i).getName();
            if (goalData.getTableheaderList().get(i).isSort()) {
                int index = GoalsUtils.getIndex(goalData.getTableBodyList().get(0),
                        goalData.getTableheaderList().get(i).getKey());
                setColumnComparator(i, TableComparator.getBodyComparator(index));
            }
        }`

As you can see I have used array to display headers and body is also displayed in different code in same manner. Also I have used Column Comparator in the loop itself to sort the columns according to data. This is my Table comparator class:

`public static Comparator<List<TableBody>> getBodyComparator(int index) {
        headerIndex = index;
        return new BodyComparator();
    }

    private static class BodyComparator implements Comparator<List<TableBody>> {

        @Override
        public int compare(final List<TableBody> body1, final List<TableBody> body2) {
            return body1.get(headerIndex).getValue().compareTo(body2.get(headerIndex).getValue());
        }
    }`

Now the issue is that I am always getting headerIndex in above code fixed. My question how to get it dynamically. How Can I detect if user has clicked the header for sorting? Please help.

**Comment by sirajsolutelabs** [comment]
The issue is fixed. the approach taken for dynamic sorting is anyone stuck like me:

`for (int i = 0; i < goalData.getTableheaderList().size(); i++) {
            tableColumnModel.setColumnWidth(i, 400);
            myarray[i] = goalData.getTableheaderList().get(i).getName();
            if (goalData.getTableheaderList().get(i).isSort()) {
                int index = GoalsUtils.getIndex(goalData.getTableBodyList().get(0),
                        goalData.getTableheaderList().get(i).getKey());
                setColumnComparator(i, new TableComparator(index));
            }
        }`

and the TableComparator class as follows:

`public final class TableComparator implements Comparator<List<TableBody>> {

    private int headerIndex;

    public TableComparator(int index) {
        headerIndex = index;
    }

    @Override
    public int compare(final List<TableBody> body1, final List<TableBody> body2) {
        return body1.get(headerIndex).getValue().compareTo(body2.get(headerIndex).getValue());
    }
}`

**Comment by ISchwarz23** [comment]
I still didn't understand the issue, as the table will automatically sort the table data, when the user clicks the header of a certain column. Therefor the comparator that has been set for this column is used.  
But if this issue is fixed for you, I'll close the issue.

**Comment by sirajsolutelabs** [comment]
Yes there was no issue in the library. It was my data which needs to be done sorting according to header index. Using above code for comparator, I fixed that. Thanks for your concern. Also Can you please look at #79 ?
