### ISSUE TITLE
Is any way can fixed table header?

### ISSUE THREAD

**Issue by KagayamaKaede** [ISchwarz23/SortableTableView#8]
Is any way can fixed table header?

**Comment by ISchwarz23** [comment]
Hi KagayamaKaede,  
could you please explain me in detail what you expect the table header to do?  
Thanks! :)

**Comment by KagayamaKaede** [comment]
Yes.
Like Excel,can adjustable column width.

**Comment by ISchwarz23** [comment]
Just to be sure that I understand you correctly:

You want to have the possibility to give the column width of certain columns as an absolute value (e.g. px or dp).

**Comment by esakia** [comment]
ISchwarz23 , thank you for the table! It is great. However, how do I change header text size? It is too big and it doesn't fit on the screen. I was hoping for something like table_view.setHeaderTextSize(<text size int>);

**Comment by ISchwarz23** [comment]
Hi esakia,   
in the future please open a new issue if you have an question to be answered :)   
To answer your question: it is already possible to set the header text size. As the TableView is developed in Model-View-Adapter pattern, you can implement your own `TableHeaderAdapter`. By extending the `TableHeaderAdapter` you have to implement the abstract method called `public View getHeaderView(final int columnIndex, final ViewGroup parentView)` which allows you to give any kind of view for any column. This means you could for example use a `ImageView`s as headers for your table.   
If you only feel the need to have the TableHeader text in a different size you can use the already existing `SimpleTableHeaderAdapter`. It allows you to show an array of Strings as table header. It also provides the possibility to change the text size by using the method `setTextSize(int textSize)`.   
Best regards,
Ingo

**Comment by esakia** [comment]
Hi ISchwarz23,

Thank you so much for your detailed response. Everything worked out perfect!
