### ISSUE TITLE
How i can add margin to element of SortableTableView

### ISSUE THREAD

**Issue by ryodoo** [ISchwarz23/SortableTableView#80]
Hi 

I went add two button in renderButton add add margin look the image 
![a](https://cloud.githubusercontent.com/assets/9296498/21559751/c8cfa576-ce49-11e6-911b-06959df408c8.jpg)

i weel change button voir with two button like this 
![b](https://cloud.githubusercontent.com/assets/9296498/21559763/136caf3e-ce4a-11e6-995c-b7f6f99e2914.jpg)

this is my code 

`package ma.icoz.esna.esna.fragment;

import android.content.Context;
import android.os.Bundle;
import android.os.Environment;
import android.support.v4.app.Fragment;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;

import com.joanzapata.pdfview.PDFView;
import com.joanzapata.pdfview.listener.OnLoadCompleteListener;
import com.joanzapata.pdfview.listener.OnPageChangeListener;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.File;

import de.codecrafters.tableview.SortableTableView;
import de.codecrafters.tableview.TableDataAdapter;
import de.codecrafters.tableview.toolkit.SimpleTableHeaderAdapter;
import ma.icoz.esna.esna.Accueil;
import ma.icoz.esna.esna.R;
import ma.icoz.esna.esna.conf.Variable_general;

import static ma.icoz.esna.esna.R.id.tableView;

/**
 * A simple {@link Fragment} subclass.
 */
public class BrochureFragment extends Fragment implements OnLoadCompleteListener, OnPageChangeListener {

    View view;
    Button annuler;
    SortableTableView sortableTableView;

    public BrochureFragment() {
        // Required empty public constructor
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        ((Accueil) getActivity()).setActionBarTitle("Brochures");
        view= inflater.inflate(R.layout.fragment_brochure, container, false);
        annuler = (Button)view.findViewById(R.id.annuler);
        annuler.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                PDFView pdfview;
                pdfview = (PDFView) view.findViewById(R.id.pdfview);
                sortableTableView.setVisibility(View.VISIBLE);
                pdfview.setVisibility(View.INVISIBLE);
                annuler.setVisibility(View.INVISIBLE);

            }
        });

        sortableTableView = (SortableTableView) view.findViewById(tableView);
        sortableTableView.setHeaderAdapter(new SimpleTableHeaderAdapter(BrochureFragment.this.getActivity(),"Brochure","Gamme","Voir","file"));
        sortableTableView.setColumnCount(3);

        if(Variable_general.json_brochure != null) {
            String[][] clients = new String[Variable_general.json_brochure.length()][];
            for (int i = 0; i < Variable_general.json_brochure.length(); i++) {
                JSONObject jo = null;
                JSONObject gamme = null;
                try {
                    jo = Variable_general.json_brochure.getJSONObject(i).getJSONObject("Brochure");
                    String game=jo.getString("game_id");
                    for (int j = 0; j < Variable_general.json_gammes.length(); j++) {
                        gamme = Variable_general.json_gammes.getJSONObject(j).getJSONObject("Game");
                        if(gamme.getString("id").equals(game))
                        {
                            game=gamme.getString("name");
                            break;
                        }
                    }
                    String[] client = new String[]{jo.getString("name"),
                            game,"Voir",jo.getString("file")};
                    clients[i] = client;
                } catch (JSONException e) {
                    e.printStackTrace();
                }
            }
            BrochureFragment.ClientTableDataAdapter clientss = new BrochureFragment.ClientTableDataAdapter(BrochureFragment.this.getActivity(), clients);
            sortableTableView.setDataAdapter(clientss);
        }

        return view;

    }

    public class ClientTableDataAdapter extends TableDataAdapter<String[]> {
        public ClientTableDataAdapter(Context context, String[][] data) {
            super(context, data);
        }

        public View getCellView(int rowIndex, int columnIndex, ViewGroup parentView) {
            final String[] client = getRowData(rowIndex);
            View renderedView = null;

            switch (columnIndex) {
                case 0:
                    renderedView = renderTextView( client[0],client[3]);
                    break;
                case 1:
                    renderedView = renderTextView( client[1], client[3]);
                    break;
                case 2:
                    renderedView = renderButton( client[2], client[3]);
                    break;
            }

            return renderedView;
        }

        private Button renderButton(String label, final String id ) {
            Button button = new Button( getContext() );
            button.setText( label );
            button.setGravity(Gravity.CENTER);
            button.setBackgroundDrawable( getResources().getDrawable(R.drawable.button));
            button.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View viewIn) {
                    showPdf(id);
                }
            });
            return button;
        }

        private View renderTextView(String label , final String id) {
            TextView textView = new TextView( getContext() );
            textView.setText(label);
            textView.callOnClick();
            textView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View viewIn) {
                    showPdf(id);
                }
            });
            return textView;
        }

    }

    public void showPdf(String fil)
    {
        File pdfFile = new File(Environment.getExternalStorageDirectory() + "/brochures/" + fil);  // -> filename = maven.pdf
        PDFView pdfview;
        pdfview = (PDFView) view.findViewById(R.id.pdfview);
        sortableTableView.setVisibility(View.INVISIBLE);
        pdfview.setVisibility(View.VISIBLE);
        Button annuler = (Button) view.findViewById(R.id.annuler);
        annuler.setVisibility(View.VISIBLE);
        pdfview.fromFile(pdfFile).defaultPage(1).showMinimap(false).enableSwipe(true).onLoad(this).onPageChange(this)
                .load();
    }

    @Override
    public void loadComplete(int nbPages) {

    }

    @Override
    public void onPageChanged(int page, int pageCount) {

    }
}
`
Mercii

**Comment by ISchwarz23** [comment]
Hi @ryodoo ,

if I understood you correctly, all you want to do is change the last collumn to show two buttons (with some margin) instead of one. Is this correct?

Best regards,
Ingo
