### ISSUE TITLE
Is is possible to update the underlying data without change the scroll position?

### ISSUE THREAD

**Issue by bilthon** [ISchwarz23/SortableTableView#81]
Basically that, I've been playing around with both the SortableTableView class and my custom adapter, but couldn't manage to make any update  to preserve the current scroll position of the listview.

**Comment by ISchwarz23** [comment]
Hi @bilthon,

as I know, the scroll position is already preserved. How are you updating your data inside the table?

Best regards,
Ingo

**Comment by bilthon** [comment]
I'm keeping a reference of the TableDataAdapter and then calling:
```

clear()
addAll()
notifyDataSetChanged()
```

I guess this might be the problem right? I should just add the new elements and avoid clearing it I suppose?

Best regards
Nelson

**Comment by ISchwarz23** [comment]
Hi Nelson,

yes, I think this is the issue. Please tell me if this fixed the issue.

Best regards,
Ingo

**Comment by bilthon** [comment]
Hi @ISchwarz23 ! yes it did! Thanks for the tip! and I'll just close this silly issue now.
