### ISSUE TITLE
How can i setOnScrollListener for listview

### ISSUE THREAD

**Issue by sherzodbek2557791** [ISchwarz23/SortableTableView#82]
How can i setOnScrollListener for listview
i need to add EndlessOnScrollListener

**Comment by ISchwarz23** [comment]
Hi @tima2557791,

the feature is currently developped. Also an EndlessOnScrollListener will be part of the next version.

Best regards,
Ingo

**Comment by ISchwarz23** [comment]
Hi @tima2557791,

I just released version 2.5.0 which is containing the requested feature. Give it a try :)

Best regards,
Ingo
