### ISSUE TITLE
Nested Scrolling

### ISSUE THREAD

**Issue by sunnykinger** [ISchwarz23/SortableTableView#83]
The library is amazing. 
I have more than 10 columns and because of that I had to use the Horizontal Scroll View with nestedScrollingEnabled attribute enabled for the TableView. This combination works great, but nested scrolling is only available for API 21 and above, so is it possible that it can be enabled for API below 21?

**Comment by meekzhou** [comment]
Hi，How to achieve horizontal scrolling？I tried a lot of ways, did not solve this problem

**Comment by fernandodeveloper** [comment]
I need this horizontal scrolling too!

**Comment by ISchwarz23** [comment]
Hi,

1) set a `TableColumnDpWidthModel` or `TableColumnPxWidthModel` so you are able to have a table that is wider than your screen by setting the width for each column.
2) put your `TableView` inside a `HorizontalScrollView`

Best regards,
Ingo
