### ISSUE TITLE
Use SortableTableView with toolbar

### ISSUE THREAD

**Issue by magiclen** [ISchwarz23/SortableTableView#84]
SortableTableView is very awesome! However, I have tried some ways to hide/show my toolbar when scrolling the SortableTableView. It is difficult to check the direction scrolled by users.

I want to hide my toolbar when the SortableTableView is scrolling, and show it back when the user scrolls to the top of the SortableTableView. How should I do? I don't know how to check the scroll bar position whether it is at the top.

**Comment by ISchwarz23** [comment]
Hi @magiclen,

since the version 2.5.0 the TableView provides the possibility to add an `OnScrollListener`. Is this sufficient for you?

Best regards,
Ingo

**Comment by magiclen** [comment]
I finished it. I share my code below.

    @Override
    public void onScroll(final ListView tableDataView, final int firstVisibleItem, final int visibleItemCount, final int totalItemCount) {
        isAtTop = false;
        isAtBottom = false;

        if (firstVisibleItem == 0) {
            final View v = tableDataView.getChildAt(0);
            int offset = (v == null) ? 0 : v.getTop();
            if (offset == 0) {
                isAtTop = true;
            }
        }
        final int endVisibleItem = firstVisibleItem + visibleItemCount;
        if (endVisibleItem >= totalItemCount) {
            final View v = tableDataView.getChildAt(visibleItemCount - 1);
            int offset = (v == null) ? 0 : tableDataView.getHeight() - (v.getTop() + v.getHeight());
            if (offset == 0) {
                isAtBottom = true;
            }
        }

        if (isAtTop) {
            tableDataView.postDelayed(new Runnable() {
                @Override
                public void run() {
                    if (isAtTop && !ab.isShowing() && !isScrolling) {
                        ab.show();
                    }
                }
            }, SHOW_HIDE_ACTIONBAR_DELAY);
        } else {
            tableDataView.postDelayed(new Runnable() {
                @Override
                public void run() {
                    if (!isAtTop && ab.isShowing() && !isScrolling) {
                        if (!isAtBottom) {
                            tableDataView.smoothScrollBy(-actionBarHeight, 1);
                        }
                        ab.hide();
                    }
                }
            }, SHOW_HIDE_ACTIONBAR_DELAY);
        }
    }

    @Override
    public void onScrollStateChanged(final ListView tableDateView, final ScrollState scrollState) {
        switch (scrollState) {
            case TOUCH_SCROLL:
                isScrolling = true;
                break;
            case IDLE:
                isScrolling = false;
                break;
        }
    }

In **onScroll** method, I check whether the TableView is at top or bottom. The **ab** variable is an ActionBar(ToolBar) object. **SHOW_HIDE_ACTIONBAR_DELAY** is an integer constant .

**Comment by ISchwarz23** [comment]
Thank you for sharing your code 👍
