### ISSUE TITLE
How to get the Clicked columnIndex?

### ISSUE THREAD

**Issue by rohitbhoite** [ISchwarz23/SortableTableView#85]
With TableDataClickListener it is possible to get rowindex. I want to store different type of data in each cell.How to get the clicked columnIndex and RowIndex to identify the clicked object in easy manner?

**Comment by ISchwarz23** [comment]
Hi @rohitbhoite,

long time ago, I decided explizitly against a click listener that provides the column index, as in a table all columns in a row belong to the same data item.
Can you explain the workflow from user point of view for which you need the column index?

Best regards,
Ingo

**Comment by rohitbhoite** [comment]
Please consider the following scenario.
I have 5 columns  and 10 rows.i.e,I have 50 cells.On click of particular cell,I want to assign particular object(Image of a person) to the cell(kind of seat arrangement).I would like to implement this scenario.Any help is appreciated.

Thanks,
Rohit

**Comment by ISchwarz23** [comment]
Hi Rohit,

in my opinion the use-case described by you isn't one that should be implemented using a table. I think what you need is a set of independent cells, which is not the case in a table. In a table all cells in a row belong to the same data item.
I woukd recommend to implement your use case using a certain grid (e.g. a custom GridLayout).
Don't you agree?

Best regards,
Ingo

**Comment by mesutd0nmez** [comment]
Hey buddy, if tableview doesn't support to get it, write ur own functions as below. 

1- Create a class named InterfaceModel and write below code inside it.

public interface setCellOnClick{
        void onClick(View view, int rowIndex, int columnIndex);
}

2- Go ur Fragment or Activity that write below code. I did example in Fragment therefore i used below code in ActivityCreated method.

public static InterfaceModel.setCellOnClick itemClick = null;
itemClick = new InterfaceModel.setCellOnClick() {
            @Override
            public void onClick(View view, int rowIndex, int columnIndex) {
                Toast.makeText(getActivity(), "rowIndex: " + rowIndex + " columnIndex: " + columnIndex, Toast.LENGTH_SHORT).show();
            }
};

3- Last step is go ur data adapter class and write below code to send data to ur own Activity or Fragment
renderedView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                EndorsementFragment.itemClick.onClick(renderedView, rowIndex, columnIndex);
            }
});

So buddy u can receive it all. If u want, u can also use view to receive data information too, or set data. I hope i helped u.
