### ISSUE TITLE
Horizontal Scrolling and Vertical Line Divider

### ISSUE THREAD

**Issue by Sp4Rx** [ISchwarz23/SortableTableView#86]
I had a table with 7 columns and containing long header names and data also. So I want to add this table view inside a horizontal scroll view but it is not working properly as the vertical scrolling of the table is blocked by the horizontal scrolling. Please show my a direction to achieve this.

And I also want to add vertical line divider between each column.

**Comment by meekzhou** [comment]
Hi，How to achieve horizontal scrolling？I tried a lot of ways, did not solve this problem

**Comment by rohan2817** [comment]
I am also stuck with the same issue, what could be the solution for this?

**Comment by mbsysde** [comment]
This is worked for me

`<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
                  xmlns:custom="http://schemas.android.com/apk/res-auto"
                  xmlns:tools="http://schemas.android.com/tools"
                  android:id="@+id/fragment_data_sync"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"
                  android:orientation="vertical"
                  tools:context="id.ctech.pos.fragment.tabs.settings.DataSyncFragment">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/fab_margin"
            android:orientation="vertical">

            <TextView
                android:id="@+id/bank_server_textview"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="@string/bank_server_title"
                android:textSize="16sp"
                android:textStyle="bold"/>

            <android.widget.HorizontalScrollView
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <id.ctech.pos.fragment.tabs.settings.data_sync.bank_server.BankSortableTableView
                    android:id="@+id/bank_server_table"
                    android:layout_width="900dp"
                    android:layout_height="100dp"
                    android:layout_marginTop="8dp"
                    custom:tableView_columnCount="6"
                    custom:tableView_headerColor="@color/blue_700"
                    custom:tableView_headerElevation="10"/>
            </android.widget.HorizontalScrollView>

            <LinearLayout
                xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="match_parent"
                android:layout_height="50dp"
                android:layout_marginLeft="400dp"
                android:orientation="horizontal">

                <Button
                    android:id="@+id/bank_new_button"
                    style="?android:attr/buttonBarStyle"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_margin="3dp"
                    android:layout_weight="1"
                    android:background="@drawable/button_pattern"
                    android:text="@string/new_text_button"
                    android:textColor="@color/white"
                    android:textSize="14sp"/>

                <Button
                    android:id="@+id/bank_edit_button"
                    style="?android:attr/buttonBarStyle"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_margin="3dp"
                    android:layout_weight="1"
                    android:background="@drawable/button_pattern"
                    android:text="@string/edit_text_button"
                    android:textColor="@color/white"
                    android:textSize="14sp"/>

                <Button
                    android:id="@+id/bank_delete_button"
                    style="?android:attr/buttonBarStyle"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_margin="3dp"
                    android:layout_weight="1"
                    android:background="@drawable/button_pattern"
                    android:text="@string/delete_text_button"
                    android:textColor="@color/white"
                    android:textSize="14sp"/>

            </LinearLayout>
        </LinearLayout>

    </LinearLayout>

</ScrollView>`

**Comment by allanwxm** [comment]
Add this in your custom subclass of SortableTableView and then put it in a HorizontalScrollView. This can solve the problem that the vertical scrolling of the table is blocked by the horizontal scrolling.

**Comment by Sp4Rx** [comment]
@allanwxm +1
Thank you for this , it gives a better scrolling experience.

**Comment by DiegoRicardoValdiviaArreola** [comment]
I also found this [answer](https://github.com/ISchwarz23/SortableTableView/issues/72#issuecomment-269465721) from @sirajsolutelabs

You have to add android:nestedScrollingEnabled="true" in the SortableTableView xml element
