### ISSUE TITLE
Empty table message

### ISSUE THREAD

**Issue by daniftodi** [ISchwarz23/SortableTableView#87]
Hi,

How can I set a default message to be displayed when table contains no data ?

Thanks.

**Comment by daniftodi** [comment]
Are there some news about this requirement ?

**Comment by ISchwarz23** [comment]
Hi @daniftodi,

try the latest version of the tableview (version 2.6.0). You can use the `setEmptyDataIndicatorView` method to achive the requested behavior. For more information have a look to the readme.

Best regards,
Ingo
