### ISSUE TITLE
Keep selected and multiselect

### ISSUE THREAD

**Issue by marianolc** [ISchwarz23/SortableTableView#89]
Hi, Is there any way to keep selected a row after it was clicked?

**Comment by erwinyn99** [comment]
`public class CarTableDataAdapter extends TableDataAdapter<Car> {
	private static int _selectedRowIdx = -1;

	public CarTableDataAdapter(Context context, List<Car> data) {
		super(context, data);
	}

	@Override
	public View getCellView(int rowIndex, int columnIndex, ViewGroup parentView) {
		Car car = getRowData(rowIndex);
		View renderedView = null;

		switch (columnIndex) {
			case 0:
				renderedView = renderProducerLogo(car);
				break;
			case 1:
				renderedView = renderCatName(car);
				break;
			case 2:
				renderedView = renderPower(car);
				break;
			case 3:
				renderedView = renderPrice(car);
				break;
		}

		if (_selectedRowIdx == rowIndex && _selectedRowIdx >= 0 && renderedView != null) {
			renderedView.setBackgroundColor(getResources().getColor(R.color.orange_A100));
		}

		return renderedView;
	} 
	
	public void setSelectedColor(int rowIndex) {
		_selectedRowIdx = rowIndex;
	}     
}`

**Comment by ISchwarz23** [comment]
Hi @marianolc,

if there are still open points, we'll discuss it in issue #38.

Best regards,
Ingo
