### ISSUE TITLE
the last row missing, when i put the sortabletableview in the fragment of viewpager

### ISSUE THREAD

**Issue by abinla** [ISchwarz23/SortableTableView#9]

**Comment by ISchwarz23** [comment]
Hi abinla,  
could you please provide some code of you issue. Otherwise I have now possibility to find the root cause for the missbehavior.  
Thanks! :)

**Comment by systemstart** [comment]
maybe related: i can't scroll the table view if it's inside a viewpager.

please check 4ca3d8f6518a32bb13f584ee70791f7332c4ea23 for an example.

any hint?

**Comment by ISchwarz23** [comment]
I have created a small example where I put 5 SortableTableViews inside a ViewPager following this [example](https://developer.android.com/training/animation/screen-slide.html#viewpager) and it worked properly. I have used the latest version of the TableView (2.0.1).

**Comment by systemstart** [comment]
can you provide the example you built?
