### ISSUE TITLE
Indicator on table header is not listening to user's user interaction.

### ISSUE THREAD

**Issue by axiom88-guru** [ISchwarz23/SortableTableView#93]
Sample is working fine but in my app, everytime I click the table header, the table is not sorted ascending with given comparator. Even, the color of indicator is not being changed.

**Comment by ISchwarz23** [comment]
Hi @axiom88-guru,

could you share some code?

Besteht regards,
Ingo

**Comment by axiom88-guru** [comment]
Hi Ingo, thanks for your interest. 

Fortunately, I had the same idea like what you did in your example code. It works fine.
I just copied the whole code and changed a little bit regarding Class names. 
Here are some ...

**-In the Activity**

        final SortableTransactionTableView transactionTableView = (SortableTransactionTableView) findViewById(R.id.tableView);
        if (transactionTableView != null) {
            final TransactionTableDataAdapter transactionTableDataAdapter = new TransactionTableDataAdapter(this, results);
            transactionTableView.setDataAdapter(transactionTableDataAdapter);
        }

**-SortableTransactionTableView**

ublic class SortableTransactionTableView extends SortableTableView<Transaction>{

    public SortableTransactionTableView(final Context context) {
        this(context, null);
    }

    public SortableTransactionTableView(final Context context, final AttributeSet attributes) {
        this(context, attributes, android.R.attr.listViewStyle);
    }

    public SortableTransactionTableView(final Context context, final AttributeSet attributes, final int styleAttributes) {
        super(context, attributes, styleAttributes);

        final SimpleTableHeaderAdapter simpleTableHeaderAdapter = new SimpleTableHeaderAdapter(context, R.string.th_date, R.string.th_employee, R.string.th_price, R.string.th_tip);
//        simpleTableHeaderAdapter.setPaddings(16,15,16,15);
        simpleTableHeaderAdapter.setTextColor(ContextCompat.getColor(context, R.color.table_header_text));
        setHeaderAdapter(simpleTableHeaderAdapter);

        final int rowColorEven = ContextCompat.getColor(context, R.color.table_data_row_even);
        final int rowColorOdd = ContextCompat.getColor(context, R.color.table_data_row_odd);
        setDataRowBackgroundProvider(TableDataRowBackgroundProviders.alternatingRowColors(rowColorEven, rowColorOdd));
        setHeaderSortStateViewProvider(SortStateViewProviders.brightArrows());

        final TableColumnWeightModel tableColumnWeightModel = new TableColumnWeightModel(4);
        tableColumnWeightModel.setColumnWeight(0, 2);
        tableColumnWeightModel.setColumnWeight(1, 3);
        tableColumnWeightModel.setColumnWeight(2, 3);
        tableColumnWeightModel.setColumnWeight(3, 2);
        setColumnModel(tableColumnWeightModel);

        setColumnComparator(0, TransactionComparators.getTransactionPriceComparator());
        setColumnComparator(1, TransactionComparators.getTransactionPriceComparator());
        setColumnComparator(2, TransactionComparators.getTransactionPriceComparator());
        setColumnComparator(3, TransactionComparators.getTransactionPriceComparator()); // Sort ability to Tip
    }

- TransactionComparators

public final class TransactionComparators {

    private TransactionComparators() {
        //no instance
    }

    public static Comparator<Transaction> getTransactionPriceComparator() {
        return new TransactionPriceComparator();
    }

    private static class TransactionPriceComparator implements Comparator<Transaction> {

        @Override
        public int compare(final Transaction tran1, final Transaction tran2) {
            if (tran1.getTipAmount() < tran2.getTipAmount()) return 1;
            if (tran1.getTipAmount() > tran2.getTipAmount()) return -1;
            return 0;
        }
    }

}

Do you see any difference here? 
Thanks in advance.
Best 
Wira

**Comment by axiom88-guru** [comment]
I was implementing sort comparator for Realm data model.
