### ISSUE TITLE
Is there a way to refresh the tableview? 

### ISSUE THREAD

**Issue by axiom88-guru** [ISchwarz23/SortableTableView#94]
Hi there, 
Thanks for the great library, it has been very helpful for my project. 
Anyway, I couldn't figure out the way to refresh the tableview with new data. 
            
transactionTableDataAdapter = new TransactionTableDataAdapter(this, transactionList); transactionTableView.setDataAdapter(transactionTableDataAdapter);

If I fresh the data in transactionList , tableview would also be refreshed? 
Please let me know
Thanks

**Comment by axiom88-guru** [comment]
I found this method don't work.
transactionTableDataAdapter.notifyDataSetChanged();

**Comment by mbsysde** [comment]
It's working for me
```
transactionTableDataAdapter = new TransactionTableDataAdapter(this, transactionList); transactionTableView.setDataAdapter(transactionTableDataAdapter);
transactionTableView.invalidate();

```

**Comment by ISchwarz23** [comment]
Hi @axiom88-guru,

I'm glad, that my table helped you. It would be very nice, if you describe in #35 for what project and how you used this TableView there.

To answer you question: The intended way of using the TableDataAdapter was to call the `notifyDataSetChanged` method. This method is also used in the example app. So may you have a look at the example implementation https://github.com/ISchwarz23/SortableTableView/blob/master/app/src/main/java/de/codecrafters/tableviewexample/MainActivity.java#L44.

Best regards,
Ingo
