### ISSUE TITLE
Change SortableTableView cell values in edit mode

### ISSUE THREAD

**Issue by erwinyn99** [ISchwarz23/SortableTableView#95]
How to change SortableTableView cell values in edit mode? 

`void editMode(){
   // edit mode proccessing ????
}

Button newButton = (Button) rootView.findViewById(R.id.new_button);
if (newButton != null) {
	editMode();
}
`

**Comment by ISchwarz23** [comment]
Hi @erwinyn99,

I'm not sure if I got you correctly. I understood, that you are able to enter the edit mode, but you are not sure how to apply the new values that have been entered by the user. Is this correct?

Best regards,
Ingo

**Comment by mbsysde** [comment]
Yes, its correct.
For editing by creating a new row in the database then display the new row into the tableview at the last row (bottom), and then for the edit by pressing the row of the tableview with a long duration.

I want the reversed process.

When the edit button is pressed, then the selected line will display the edit view text. Then just when the save button is pressed the data is saved to the database. Is that possible?

**Comment by ISchwarz23** [comment]
Yes, this is possible but of cause not natively supported as any user wants to have a different behavior here.

Here is how I would implement it:
1. Have a toolbar (or something else) that shows an edit button when a certain row is selected.
2. When the edit button is pressed, it'll tell the TableDataAdapter, which row shall be edited an triggers a new styling (e.g. via notifyDataSetChanged()) and the toolbar changes to show an apply and cancle button.
3. a. When the apply button is pressed, the data entered by the user will be requested from the TableDataAdapter and saved. In addition we tell the TableDataAdapter that nothing shall be rendered in edit mode and a new styling is triggered.
b. When the cancle button is pressed, we tell the TableDataAdapter that nothing shall be rendered in edit mode and a new styling is triggered.

Does this answer your question?

Best regards,
Ingo

**Comment by mbsysde** [comment]
Yes, I understand. Thank You for point out.
