### ISSUE TITLE
How do I set the initial sorting of the table?

### ISSUE THREAD

**Issue by mahye82** [ISchwarz23/SortableTableView#96]
I've got the table working, with comparators and icons that correctly respond to user input to sort the table. 

The last thing I need to do is set the **INITIAL/DEFAULT** sorting of the table after data has been loaded, without the user having to click one of the column headers. 

How do I do this?

**Comment by mbsysde** [comment]
Look at setSortState function in ShortableTableHeaderView.java

**Comment by erwinyn99** [comment]
`YourTableView.sort(0, true); // 0= columnIndex will be sort, true = sortAscending`

**Comment by mahye82** [comment]
@erwinyn99 Thanks, that worked. 

@ISchwarz23 Great resource - thanks for creating it.
