### ISSUE TITLE
The row disappears when long pressed in the SortableTableView

### ISSUE THREAD

**Issue by Sineth-N** [ISchwarz23/SortableTableView#98]
Hi all,
I've used the SortableTableView in one of my apps and the users claim that the table rows disappear when long pressed on the row. I have set the `sortableTableView.setLongClickable(false);` as well.
Next I added longPressListeners which return true as well just to make sure nothing is left unchecked.
```
        sortableTableView.setOnLongClickListener(new View.OnLongClickListener() {
            @Override
            public boolean onLongClick(View v) {
                return true;
            }
        });
        sortableTableView.addDataLongClickListener(new TableDataLongClickListener<RecordView>() {
            @Override
            public boolean onDataLongClicked(int rowIndex, RecordView clickedData) {
                return true;
            }
        });
    <de.codecrafters.tableview.SortableTableView
        android:id="@+id/tableView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#dafdea"
        table:tableView_columnCount="7"
        table:tableView_headerColor="@color/colorAccent"
        table:tableView_headerElevation="10" />
```
@ISchwarz23 
Is there anything that I'm doing wrong here or is it a problem with the library? Any help on this is highly appreciated and valued.
Thanks,
Sineth.

**Comment by ISchwarz23** [comment]
Hi @Sineth-N,

what kind of TableDataAdapter are you implementing? An ordinary `TableDataAdapter` or are you extending the `LongPressAwareTableDataAdapter`?

Best regards,
Ingo

**Comment by Sineth-N** [comment]
I'm using an adapter class which extends `LongPressAwareTableDataAdapter` and I'm overriding the getLongPressCellView method as follows, is that why this happens??
```
    @Override
    public View getLongPressCellView(int rowIndex, int columnIndex, ViewGroup parentView) {
        return null;
    }

```

**Comment by ISchwarz23** [comment]
This is the issue! On long press, all cells are rendered empty as you are returning null. If you don't need this feature, it is enough to extend the `TableDataAdapter`.

**Comment by Sineth-N** [comment]
@ISchwarz23,
it worked!!
Thanks mate, for the quick reply 👍 and for the awesome library..
