### ISSUE TITLE
Problem with table view.

### ISSUE THREAD

**Issue by renevl** [ISchwarz23/SortableTableView#99]
Im using this control but when I try to show the data in the tableview, it doesn´t appear anything.

` table_products.setVisibility(View.VISIBLE);
  table_adapter=new cTableAdapter(getBaseContext(),res_array.get(4));      
  table_adapter.setData_array(res_array.get(4));
  table_products.setDataAdapter(table_adapter);
`
`public class cTableAdapter extends TableDataAdapter<Object[]>
{

    private ArrayList<Object[]>data_array;
    public cTableAdapter(Context context, ArrayList<Object[]> data) {
        super(context, data);
    }

    public void setData_array(ArrayList<Object[]> data_array) {
        this.data_array = data_array;
    }

    @Override
    public View getCellView(int rowIndex, int columnIndex, ViewGroup parentView) {
       switch (columnIndex)
       {
           case 0:return renderColumn0(parentView);
           case 1:return renderColumn1(parentView,columnIndex,rowIndex);
           default:return renderColumn2(columnIndex,rowIndex);
       }
    }

    private View renderColumn0(ViewGroup parentView)
    {
        View viewfst=getLayoutInflater().inflate(R.layout.table_view_adapter,parentView,false);
        CheckBox cellfst=(CheckBox)viewfst.findViewById(R.id.cbx_column);
        cellfst.setChecked(false);
        return viewfst;
    }
    private View renderColumn1(ViewGroup parentView,int columnIndex,int rowIndex)
    {
       View view=getLayoutInflater().inflate(R.layout.table_view_adapter_1,parentView,false);
       TextView cell=(TextView) view.findViewById(R.id.txt_column);
       cell.setText(data_array.get(rowIndex)[columnIndex].toString());
       return view;
    }
    private View renderColumn2(int columnIndex,int rowIndex)
    {
        final TextView textView = new TextView(getContext());
        textView.setText(data_array.get(rowIndex)[columnIndex].toString());
        textView.setPadding(20, 10, 20, 10);
        return textView;
    }

}
 `
I don´t know what is missing.

**Comment by ISchwarz23** [comment]
Hi @renevl,

first I would remove the `setData_array()` method to ensure the functionality of the adapter. To access the data passed via the constructor call the `getRowData(rowIndex)` method.

But the rest looks fine. May you can check if there is some data in `res_array.get(4)`.

Best regards,
Ingo

**Comment by renevl** [comment]
I removed the method and I verified the var res_array but the table still no showing data.

**Comment by mbsysde** [comment]
// Static member variableprivate static ArrayList<Object[]> data_array;

// Passing data though constructor
public cTableAdapter(Context context, ArrayList<Object[]> data) {
    super(context, data);

    this.data_array = data;
}


On 16 May 2017 9:06 p.m., "renevl" <notifications@github.com> wrote:

I removed the method and I verified the var res_array but the table still
no showing data.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ISchwarz23/SortableTableView/issues/99#issuecomment-301793298>,
or mute the thread

**Comment by renevl** [comment]
When I debugg, the list or the method getRowData return a Object array that have data but the data doesn´t showed in the tableview.

**Comment by ISchwarz23** [comment]
Please try this adapter:

```java
public class cTableAdapter extends TableDataAdapter<Object[]>{

    public cTableAdapter(Context context, ArrayList<Object[]> data) {
        super(context, data);
    }

    @Override
    public View getCellView(int rowIndex, int columnIndex, ViewGroup parentView) {
        switch (columnIndex) {
            case 0: return renderColumn0(parentView);
            case 1: return renderColumn1(parentView,columnIndex,rowIndex);
            default: return renderColumn2(columnIndex,rowIndex);
         }
    }

    private View renderColumn0(ViewGroup parentView) {
        View viewfst = getLayoutInflater().inflate(R.layout.table_view_adapter,parentView,false);
        CheckBox cellfst = (CheckBox)viewfst.findViewById(R.id.cbx_column);
        cellfst.setChecked(false);
        return viewfst;
    }

    private View renderColumn1(ViewGroup parentView,int columnIndex,int rowIndex) {
        View view=getLayoutInflater().inflate(R.layout.table_view_adapter_1,parentView,false);
        TextView cell = (TextView) view.findViewById(R.id.txt_column);
        cell.setText(getRowData(rowIndex)[columnIndex].toString());
        return view;
    }

    private View renderColumn2(int columnIndex, int rowIndex) {
        final TextView textView = new TextView(getContext());
        textView.setText(getRowData(rowIndex)[columnIndex].toString());
        textView.setPadding(20, 10, 20, 10);
        return textView;
    }
}
```

As improvement: Don't inflate the cell layouts, but create the View itself, like you did in `renderColumn2`.

**Comment by renevl** [comment]
I have my code like this:
`public class cTableAdapter extends TableDataAdapter<Object[]>
{

    private Object[]data_row;

    public cTableAdapter(Context context, ArrayList<Object[]> data) {
        super(context, data);
    }

    @Override
    public View getCellView(int rowIndex, int columnIndex, ViewGroup parentView) {
       data_row=getRowData(rowIndex);
        View renderedView;
       switch (columnIndex)
       {
           case 0:
               renderedView =renderColumn0();
           break;
           default:
               renderedView = renderColumn1(columnIndex);
           break;
       }
       return renderedView;
    }

    private View renderColumn0()
    {
       CheckBox cbx_column=new CheckBox(getContext());
       cbx_column.setChecked(false);
       return cbx_column;
    }

    private View renderColumn1(int columnIndex)
    {
        TextView textView = new TextView(getContext());
        textView.setText(data_row[columnIndex].toString());
        textView.setPadding(20, 10, 20, 10);
        return textView;
    }


}
`

**Comment by renevl** [comment]
and still no showing data
![tableview](https://cloud.githubusercontent.com/assets/28716930/26118270/e5aee552-3a2e-11e7-846a-51cb59324f10.png)

**Comment by mbsysde** [comment]
Put your cursor on front of getRowData(rowIndex) then press Shift + F9
(Debug app). What is return of getRowData? Empty or not?

**Comment by renevl** [comment]
![image](https://cloud.githubusercontent.com/assets/28716930/26119627/7d539d9a-3a33-11e7-8c2d-31d50352eddb.png)

**Comment by renevl** [comment]
getRowData has data

**Comment by ISchwarz23** [comment]
Strange. When I use the Adapter you posted most recently, I see the data.
This is how I my data:

```java
final ArrayList<Object[]> data = new ArrayList<>();
data.add(new Object[]{"This", "is", "a", "test"});

final SortableTableView<Object[]> tableView = (SortableTableView) findViewById(R.id.tableView);
tableView.setDataAdapter(new cTableAdapter(this, data));
```

And I see a table like this:
`| (ChekckBox) | is      | a       | test     |`

**Comment by renevl** [comment]
Do the table has to be SortableTableView? because I put only a TableView.

**Comment by ISchwarz23** [comment]
No, the SortableTableView just provides the possibility for the user to sort the data.

**Comment by renevl** [comment]
and Do I need to create another class? i just use the adapter and the main activity.

**Comment by ISchwarz23** [comment]
No, you don't need more. As mentioned for me it is working with the code above. I just checked it with the simple TableView and it is also working:

```java
final TableView<Object[]> tableView = (TableView) findViewById(R.id.tableView);
tableView.setDataAdapter(new cTableAdapter(this, data));
```

Can you post the layout file which contains the `TableView`?

**Comment by renevl** [comment]
`<ScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    tools:context="com.example.administrador.eagle_au.auth_order.view.au_order"
    android:id="@+id/scroll_form"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fillViewport="true"
    >
    <RelativeLayout
        android:id="@+id/lay_content_form_1"
        android:padding="15dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <com.getbase.floatingactionbutton.FloatingActionsMenu
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/menu_buttons"
            android:layout_alignParentEnd="true"
            android:layout_alignParentRight="true"
            android:layout_alignParentTop="true"
            fab:fab_expandDirection="left"
            fab:fab_addButtonColorNormal="?attr/colorPrimary"
            fab:fab_addButtonColorPressed="@color/colorPrimaryDark"
            fab:fab_addButtonSize="normal"
            android:layout_marginBottom="15dp"
            >
            <com.getbase.floatingactionbutton.FloatingActionButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/btn_search_order"
                fab:fab_size="mini"
                fab:fab_colorNormal="?attr/colorAccent"
                fab:fab_colorPressed="@color/colorPrimaryDark"
                fab:fab_icon="@drawable/search"
                />
            <com.getbase.floatingactionbutton.FloatingActionButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/btn_authorize_order"
                fab:fab_size="mini"
                fab:fab_colorNormal="?attr/colorAccent"
                fab:fab_colorPressed="@color/colorPrimaryDark"
                fab:fab_icon="@drawable/authorize"
                />
            <com.getbase.floatingactionbutton.FloatingActionButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/btn_reject_order"
                fab:fab_size="mini"
                fab:fab_colorNormal="?attr/colorAccent"
                fab:fab_colorPressed="@color/colorPrimaryDark"
                fab:fab_icon="@drawable/reject"
                />
        </com.getbase.floatingactionbutton.FloatingActionsMenu>
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:id="@+id/lay_form_au_order"
            android:layout_below="@+id/menu_buttons"
            >


            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:id="@+id/lay_spinner_filter_0"
                android:weightSum="100"
                android:layout_marginBottom="20dp">
                <Spinner
                    android:id="@+id/sp_client"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="50"
                    style="@style/spinner_style">
                </Spinner>

                <Spinner
                    android:id="@+id/sp_store"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="50"
                    style="@style/spinner_style"
                    >
                </Spinner>

            </LinearLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:id="@+id/lay_spinner_filter_1"
                android:weightSum="100"
                android:layout_marginBottom="30dp">
                <android.support.design.widget.TextInputLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="50"
                    android:id="@+id/til_document"
                    >
                    <EditText
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:id="@+id/edt_document"
                        android:singleLine="true"
                        android:hint="@string/edt_document"
                        android:inputType="number"
                        android:textColor="@color/colorPrimary"
                        />
                </android.support.design.widget.TextInputLayout>

                <Spinner
                    android:id="@+id/sp_reason"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="50"
                    android:layout_marginLeft="5dp"
                    android:layout_marginStart="5dp"
                    style="@style/spinner_style"
                    android:layout_gravity="center"
                    >
                </Spinner>

            </LinearLayout>

            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/txt_title"
                android:text="@string/txt_title"
                android:textColor="@color/colorPrimary"
                android:layout_marginBottom="5dp"
                android:visibility="gone"
            />
            <View
                android:layout_width="fill_parent"
                android:layout_height="1dp"
                android:background="@color/colorPrimaryDark"
                android:id="@+id/view_separator"
                android:layout_marginBottom="20dp"
                android:visibility="gone"
            />
            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/lay_info_order_titles"
                android:orientation="horizontal"
                android:weightSum="100"
                android:visibility="gone"
                >
                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:id="@+id/txt_document_title"
                    android:textAlignment="center"
                    android:layout_weight="37"
                    android:layout_gravity="center"
                    android:text="@string/txt_document_title"
                    android:textColor="@color/colorPrimary"
                    />
                <TextView
                    android:id="@+id/txt_client_title"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="26"
                    android:layout_gravity="center"
                    android:textAlignment="center"
                    android:text="@string/txt_client_title"
                    android:textColor="@color/colorPrimary"
                    >
                </TextView>
                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:text="@string/txt_amount_title"
                    android:id="@+id/txt_amount_title"
                    android:textAlignment="center"
                    android:layout_weight="37"
                    android:layout_gravity="center"
                    android:textColor="@color/colorPrimary"
                    />
            </LinearLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/lay_info_order"
                android:orientation="horizontal"
                android:weightSum="100"
                android:visibility="gone"
                android:layout_marginBottom="20dp"
            >
                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:id="@+id/txt_document"
                    android:textAlignment="center"
                    android:layout_weight="37"
                    android:layout_gravity="center"
                    android:textColor="@color/colorPrimary"
                />
                <Spinner
                    android:id="@+id/sp_tran_client"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="26"
                    style="@style/spinner_style"
                    >
                </Spinner>
                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:id="@+id/txt_amount"
                    android:textAlignment="center"
                    android:layout_weight="37"
                    android:layout_gravity="center"
                    android:textColor="@color/colorPrimary"
                    />
            </LinearLayout>
            <de.codecrafters.tableview.TableView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/table_products"
                android:visibility="gone"
                fab:tableView_columnCount="5"
                fab:tableView_headerElevation="5"
                fab:tableView_headerColor="@color/colorPrimary"
                >

            </de.codecrafters.tableview.TableView>
        </LinearLayout>
    </RelativeLayout>
</ScrollView>`

this is the layout.

**Comment by renevl** [comment]
<ScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    tools:context="com.example.administrador.eagle_au.auth_order.view.au_order"
    android:id="@+id/scroll_form"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fillViewport="true"
    >
    <RelativeLayout
        android:id="@+id/lay_content_form_1"
        android:padding="15dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <com.getbase.floatingactionbutton.FloatingActionsMenu
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/menu_buttons"
            android:layout_alignParentEnd="true"
            android:layout_alignParentRight="true"
            android:layout_alignParentTop="true"
            fab:fab_expandDirection="left"
            fab:fab_addButtonColorNormal="?attr/colorPrimary"
            fab:fab_addButtonColorPressed="@color/colorPrimaryDark"
            fab:fab_addButtonSize="normal"
            android:layout_marginBottom="15dp"
            >
            <com.getbase.floatingactionbutton.FloatingActionButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/btn_search_order"
                fab:fab_size="mini"
                fab:fab_colorNormal="?attr/colorAccent"
                fab:fab_colorPressed="@color/colorPrimaryDark"
                fab:fab_icon="@drawable/search"
                />
            <com.getbase.floatingactionbutton.FloatingActionButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/btn_authorize_order"
                fab:fab_size="mini"
                fab:fab_colorNormal="?attr/colorAccent"
                fab:fab_colorPressed="@color/colorPrimaryDark"
                fab:fab_icon="@drawable/authorize"
                />
            <com.getbase.floatingactionbutton.FloatingActionButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/btn_reject_order"
                fab:fab_size="mini"
                fab:fab_colorNormal="?attr/colorAccent"
                fab:fab_colorPressed="@color/colorPrimaryDark"
                fab:fab_icon="@drawable/reject"
                />
        </com.getbase.floatingactionbutton.FloatingActionsMenu>
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:id="@+id/lay_form_au_order"
            android:layout_below="@+id/menu_buttons"
            >


            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:id="@+id/lay_spinner_filter_0"
                android:weightSum="100"
                android:layout_marginBottom="20dp">
                <Spinner
                    android:id="@+id/sp_client"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="50"
                    style="@style/spinner_style">
                </Spinner>

                <Spinner
                    android:id="@+id/sp_store"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="50"
                    style="@style/spinner_style"
                    >
                </Spinner>

            </LinearLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:id="@+id/lay_spinner_filter_1"
                android:weightSum="100"
                android:layout_marginBottom="30dp">
                <android.support.design.widget.TextInputLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="50"
                    android:id="@+id/til_document"
                    >
                    <EditText
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:id="@+id/edt_document"
                        android:singleLine="true"
                        android:hint="@string/edt_document"
                        android:inputType="number"
                        android:textColor="@color/colorPrimary"
                        />
                </android.support.design.widget.TextInputLayout>

                <Spinner
                    android:id="@+id/sp_reason"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="50"
                    android:layout_marginLeft="5dp"
                    android:layout_marginStart="5dp"
                    style="@style/spinner_style"
                    android:layout_gravity="center"
                    >
                </Spinner>

            </LinearLayout>

            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/txt_title"
                android:text="@string/txt_title"
                android:textColor="@color/colorPrimary"
                android:layout_marginBottom="5dp"
                android:visibility="gone"
            />
            <View
                android:layout_width="fill_parent"
                android:layout_height="1dp"
                android:background="@color/colorPrimaryDark"
                android:id="@+id/view_separator"
                android:layout_marginBottom="20dp"
                android:visibility="gone"
            />
            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/lay_info_order_titles"
                android:orientation="horizontal"
                android:weightSum="100"
                android:visibility="gone"
                >
                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:id="@+id/txt_document_title"
                    android:textAlignment="center"
                    android:layout_weight="37"
                    android:layout_gravity="center"
                    android:text="@string/txt_document_title"
                    android:textColor="@color/colorPrimary"
                    />
                <TextView
                    android:id="@+id/txt_client_title"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="26"
                    android:layout_gravity="center"
                    android:textAlignment="center"
                    android:text="@string/txt_client_title"
                    android:textColor="@color/colorPrimary"
                    >
                </TextView>
                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:text="@string/txt_amount_title"
                    android:id="@+id/txt_amount_title"
                    android:textAlignment="center"
                    android:layout_weight="37"
                    android:layout_gravity="center"
                    android:textColor="@color/colorPrimary"
                    />
            </LinearLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/lay_info_order"
                android:orientation="horizontal"
                android:weightSum="100"
                android:visibility="gone"
                android:layout_marginBottom="20dp"
            >
                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:id="@+id/txt_document"
                    android:textAlignment="center"
                    android:layout_weight="37"
                    android:layout_gravity="center"
                    android:textColor="@color/colorPrimary"
                />
                <Spinner
                    android:id="@+id/sp_tran_client"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="26"
                    style="@style/spinner_style"
                    >
                </Spinner>
                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:id="@+id/txt_amount"
                    android:textAlignment="center"
                    android:layout_weight="37"
                    android:layout_gravity="center"
                    android:textColor="@color/colorPrimary"
                    />
            </LinearLayout>
            <de.codecrafters.tableview.TableView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/table_products"
                android:visibility="gone"
                fab:tableView_columnCount="5"
                fab:tableView_headerElevation="5"
                fab:tableView_headerColor="@color/colorPrimary"
                >

            </de.codecrafters.tableview.TableView>
        </LinearLayout>
    </RelativeLayout>
</ScrollView>

This is the layout

**Comment by ISchwarz23** [comment]
I guess the issue is, as your layout is pretty complex and the height is set to "wrap_content" the data is inside the table, but the height is 0. So you can try to set the height to an absulute value e.g. 100px.

**Comment by renevl** [comment]
Yes, that resolve my problem thank you very much

**Comment by renevl** [comment]
Now I need it when I look for different filters, the tableview will refresh. Can I do that?
